theforeman/foreman_remote_execution

app/models/concerns/foreman_remote_execution/template_relations.rb
lib/foreman_remote_execution/engine.rb

Fix templates editing

---

app/controllers/job_templates_controller.rb
app/models/input_template_renderer.rb
config/routes.rb
lib/foreman_remote_execution/engine.rb

based on https://github.com/theforeman/foreman_remote_execution/pull/6

Template rendering with preview

---

foreman_remote_execution.gemspec
lib/foreman_remote_execution/version.rb

From a discussion on the packaging PR about the doc/ directory, it's there so should we include it with the gem?

Include documentation with gem

---

db/migrate/20150827144500_change_targeting_search_query_type.rb

Strnig type was too limiting for a possible search query

change_column :targetings, :search_query, :text

---

.rubocop.yml
app/assets/javascripts/template_invocation.js
app/controllers/job_invocations_controller.rb
app/helpers/remote_execution_helper.rb
app/models/job_invocation.rb
app/models/job_invocation_composer.rb
app/views/job_invocations/_form.html.erb
config/routes.rb
lib/foreman_remote_execution/engine.rb
test/unit/job_invocation_composer_test.rb

Depends on https://github.com/theforeman/foreman_remote_execution/pull/31

Fixes #11365 - allow bookmark selection in invocation form

---

app/assets/javascripts/template_invocation.js
app/assets/stylesheets/template_invocation.css.scss
app/controllers/template_invocations_controller.rb
app/helpers/remote_execution_helper.rb
app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/lib/actions/remote_execution/run_proxy_command.rb
app/views/job_invocations/_tab_hosts.html.erb
app/views/job_invocations/_tab_overview.html.erb
app/views/job_invocations/show.html.erb
app/views/job_invocations/show.js.erb
app/views/template_invocations/_output_line.html.erb
app/views/template_invocations/show.html.erb
app/views/template_invocations/show.js.erb
config/routes.rb
foreman_remote_execution.gemspec
lib/foreman_remote_execution/engine.rb
test/unit/actions/run_proxy_command_test.rb

I plan to add some optimizations but it does not prevent others from reviewing current work. Note it depends on 
* https://github.com/theforeman/foreman-tasks/pull/136
* https://github.com/theforeman/foreman-tasks/pull/137

Fixes #11364 - Live output for template invocation and job invocation detail

---

app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/lib/actions/remote_execution/run_proxy_command.rb
foreman_remote_execution.gemspec
test/unit/actions/run_hosts_job_test.rb
test/unit/actions/run_proxy_command_test.rb

timeouts require theforeman/foreman-tasks#132

Refs #11361 - Allows to set retry count a timeout interval on a job

---

app/assets/javascripts/template_invocation.js
app/controllers/job_invocations_controller.rb
app/helpers/remote_execution_helper.rb
app/lib/actions/middleware/bind_job_invocation.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/models/job_invocation.rb
app/models/job_invocation_composer.rb
app/views/job_invocations/_form.html.erb
app/views/job_invocations/_tab_hosts.html.erb
app/views/job_invocations/_tab_overview.html.erb
test/unit/actions/run_hosts_job_test.rb
test/unit/actions/run_proxy_command_test.rb
test/unit/job_invocation_composer_test.rb
test/unit/job_invocation_test.rb

requires theforeman/foreman-tasks#131

Refs #10753 - Support for setting future time of execution

---

app/assets/stylesheets/template_invocation.css.scss
app/controllers/job_invocations_controller.rb
app/controllers/template_invocations_controller.rb
app/helpers/remote_execution_helper.rb
app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_proxy_command.rb
app/views/job_invocations/show.html.erb
app/views/job_invocations/show.js.erb
app/views/template_invocations/_output_line.html.erb
app/views/template_invocations/_output_line_set.html.erb
app/views/template_invocations/_refresh.js.erb
app/views/template_invocations/show.html.erb
app/views/template_invocations/show.js.erb
foreman_remote_execution.gemspec
test/unit/actions/run_proxy_command_test.rb

Also include debug data in the output (for example when the host, or the proxy
is not approachable)

Fixes #11895 - Better error handling for the live output

---

app/models/job_template.rb

Small refactor, we can create templates locked initially now that https://github.com/theforeman/foreman/pull/2652 is merged and released.

fixes #11620 - create template in one step

---

app/models/concerns/foreman_remote_execution/errors_flattener.rb
app/models/job_invocation.rb
app/models/job_invocation_api_composer.rb
app/models/template_invocation.rb
app/models/template_invocation_input_value.rb
test/unit/job_invocation_api_composer_test.rb

Also, make the API error message more descriptive, when some issue is there on
provided inputs.

Fixes #12064 - allow empty values for non-required inputs

---

app/models/job_template.rb
test/unit/job_template_test.rb

**Problem**
People come to the repo and don't know how to install the project, what does it exactly do, etc.. People ask in #theforeman IRC channel about basic help on how to install the plugin because they didn't see any documentation in the README.
**Solution**
Add a few basic information screenshots, points of contact, and links to the manual to ensure new users don't get lost.

Update README to include features, link to manual

---

app/assets/javascripts/template_invocation.js
app/controllers/job_invocations_controller.rb
app/models/job_invocation_composer.rb
app/views/job_invocations/_form.html.erb
app/views/job_invocations/_preview_hosts_list.html.erb
app/views/job_invocations/_preview_hosts_modal.html.erb
config/routes.rb
lib/foreman_remote_execution/engine.rb

I have a really hard time working with javascript so I yoinked this one since it seemed simple enough to try to learn how to do it.
Does it make sense?
One thing I think I'm lacking is I'd probably like to replace the button icon with the spinny waiting thing while it's making the ajax request.  Do you know of any examples in foreman of it doing that?

fixes #12308 - preview hosts in invocation creation

---

app/controllers/api/v2/job_invocations_controller.rb
app/controllers/api/v2/job_templates_controller.rb
app/controllers/api/v2/template_inputs_controller.rb
app/models/job_invocation.rb
app/models/job_invocation_api_composer.rb
app/models/template_input.rb
app/views/api/v2/job_invocations/base.json.rabl
app/views/api/v2/job_invocations/index.json.rabl
app/views/api/v2/job_invocations/main.json.rabl
app/views/api/v2/job_invocations/show.json.rabl
app/views/api/v2/job_templates/base.json.rabl
app/views/api/v2/job_templates/index.json.rabl
app/views/api/v2/job_templates/main.json.rabl
app/views/api/v2/template_inputs/base.json.rabl
app/views/api/v2/template_inputs/create.json.rabl
app/views/api/v2/template_inputs/index.json.rabl
app/views/api/v2/template_inputs/main.json.rabl
app/views/api/v2/template_inputs/show.json.rabl
config/routes.rb
lib/foreman_remote_execution/engine.rb
test/functional/api/v2/job_invocations_controller_test.rb
test/functional/api/v2/template_inputs_controller_test.rb
test/unit/job_invocation_api_composer_test.rb

Some API tweaks for the hammer cli to work well.  Goes with https://github.com/theforeman/hammer_cli_foreman_remote_execution/pull/1.
:heavy_check_mark: TODO

refs #12490 - changes needed for hammer cli

---

app/helpers/remote_execution_helper.rb
app/models/job_invocation.rb
app/views/job_invocations/index.html.erb
foreman_remote_execution.gemspec

While it's not blocked by https://github.com/theforeman/foreman-tasks/pull/161 it would be better to get that one in first, I'd remove the TODO and use delegate instead. We'll see how fast would that PR get in, but it shouldn't blocking the review.

Fixes #12815 - unify start time information

---

app/controllers/api/v2/job_invocations_controller.rb
app/controllers/api/v2/job_templates_controller.rb
app/models/job_invocation.rb
app/views/api/v2/job_invocations/base.json.rabl
app/views/api/v2/job_templates/base.json.rabl
app/views/api/v2/job_templates/main.json.rabl
app/views/api/v2/job_templates/show.json.rabl
test/functional/api/v2/job_invocations_controller_test.rb

~~Built on top of Daniels' rails4 PR since I've migrated my dev environment.  Will rebase once https://github.com/theforeman/foreman_remote_execution/pull/96 is merged~~

fixes #12847 - api for job descriptions

---

app/models/job_invocation.rb
db/seeds.d/90-bookmarks.rb

Based on https://github.com/theforeman/foreman_remote_execution/pull/101 which is prerequisity.

Fixes #12814 - ship default bookmarks for invocations

---

app/controllers/api/v2/job_invocations_controller.rb
app/models/job_invocation_composer.rb
app/views/api/v2/job_invocations/base.json.rabl
app/views/api/v2/job_invocations/main.json.rabl
test/functional/api/v2/job_invocations_controller_test.rb

Needs the views from https://github.com/theforeman/foreman-tasks/pull/165, still a WIP, having everything not be first class citizens on JobInvocation causes so much need for hokiness.
Anyway, first shot at the API - thoughts?

fixes #12684 - introduce api for scheduling / recurring invocations

---

.rubocop.yml
.rubocop_todo.yml
app/helpers/remote_execution_helper.rb
app/lib/actions/remote_execution/helpers/live_output.rb
app/lib/actions/remote_execution/run_proxy_command.rb
app/models/concerns/foreman_remote_execution/host_extensions.rb
app/models/concerns/foreman_remote_execution/subnet_extensions.rb
app/models/input_template_renderer.rb
app/models/job_invocation.rb
app/models/job_invocation_composer.rb
app/models/job_template.rb
app/models/template_input.rb
db/migrate/20160113162007_expand_all_template_invocations.rb
doc/plugins/div_tag.rb
doc/plugins/plantuml.rb
doc/plugins/tags.rb
doc/plugins/toc.rb
test/functional/api/v2/foreign_input_sets_controller_test.rb
test/functional/api/v2/job_templates_controller_test.rb
test/functional/api/v2/template_inputs_controller_test.rb
test/unit/actions/run_proxy_command_test.rb
test/unit/input_template_renderer_test.rb
test/unit/job_invocation_composer_test.rb
test/unit/job_invocation_test.rb
test/unit/job_template_test.rb
test/unit/targeting_test.rb

Based on the failures of http://ci.theforeman.org/job/test_plugin_pull_request/2133/, which tested the rubocop PR

fixes #13317, #12538 - fix rubocop and mass assignment for foreman 1.11

---

app/views/templates/puppet_run_once.erb
db/migrate/20160127162711_reword_puppet_template_description.rb

not sure about capital letters

Fixes #13306 - reword puppet template description format

---

app/helpers/remote_execution_helper.rb
app/views/job_invocations/index.html.erb

Fixes #13148 - style statistics as on report page

---

app/lib/actions/middleware/bind_job_invocation.rb
app/models/job_invocation.rb
app/models/template_invocation.rb

Fixes #13310 - Provide deep_clone and deep_clone!

---

app/helpers/remote_execution_helper.rb

Waits for https://github.com/theforeman/foreman/pull/3407.

Fixes #14560 - Reuse foreman's core documentation helper.

---

app/models/job_invocation_composer.rb

Requires https://github.com/theforeman/foreman-tasks/commit/a637787a5d3963e2a16e57e905dc31f19ce07680

Fixes #14684 - Save end time for recurring

---

app/controllers/api/v2/foreign_input_sets_controller.rb
app/controllers/api/v2/job_templates_controller.rb
app/controllers/api/v2/remote_execution_features_controller.rb
app/controllers/api/v2/template_inputs_controller.rb
app/controllers/concerns/foreman/controller/parameters/foreign_input_set.rb
app/controllers/concerns/foreman/controller/parameters/job_template.rb
app/controllers/concerns/foreman/controller/parameters/remote_execution_feature.rb
app/controllers/concerns/foreman/controller/parameters/targeting.rb
app/controllers/concerns/foreman/controller/parameters/template_input.rb
app/controllers/job_invocations_controller.rb
app/controllers/job_templates_controller.rb
app/controllers/remote_execution_features_controller.rb
app/models/concerns/foreman_remote_execution/nic_extensions.rb
app/models/concerns/foreman_remote_execution/subnet_extensions.rb
app/models/concerns/foreman_remote_execution/template_extensions.rb
app/models/foreign_input_set.rb
app/models/job_template.rb
app/models/job_template_effective_user.rb
app/models/remote_execution_feature.rb
app/models/targeting.rb
app/models/template_input.rb
foreman_remote_execution.gemspec
lib/foreman_remote_execution/engine.rb
lib/tasks/foreman_remote_execution_tasks.rake

Fixes #16002 - convert to strong params

---

lib/foreman_remote_execution/engine.rb

Fixes #16175 - strong params incorrect for arrays and array of hashes

---

app/helpers/remote_execution_helper.rb
app/views/job_invocations/_tab_overview.html.erb
app/views/job_invocations/index.html.erb
app/views/job_invocations/show.html.erb
db/migrate/20160926225841_update_template_input_value.rb
test/unit/template_invocation_input_value_test.rb

Addresses comments in https://github.com/theforeman/foreman_remote_execution/pull/205

Fixes #15311 allow large inputs

---

app/models/concerns/foreman_remote_execution/host_extensions.rb
lib/foreman_remote_execution/engine.rb

Jenkins pass [here](http://ci.theforeman.org/job/test_plugin_matrix/2478/)

Fixes #18027 - Fix failing tests

---

app/models/remote_execution_feature.rb
test/unit/remote_execution_feature_test.rb

Slightly improved version of
https://github.com/theforeman/foreman_remote_execution/pull/211 + added tests

Fixes #17456 - save the feature only if changed

---

app/helpers/concerns/foreman_remote_execution/job_templates_extensions.rb
app/helpers/remote_execution_helper.rb
app/views/job_invocations/_host_name_td.html.erb
app/views/job_invocations/index.html.erb
app/views/remote_execution_features/index.html.erb

Otherwise, the authorization calculation could be very slow.

Fixes #18851 - provide authorizer to avoid large requests

---

app/lib/actions/remote_execution/run_hosts_job.rb
foreman_remote_execution.gemspec
test/unit/actions/run_hosts_job_test.rb

requires ~~[the foreman-tasks PR](https://github.com/theforeman/foreman-tasks/pull/229)~~ [foreman-tasks/236](https://github.com/theforeman/foreman-tasks/pull/236) and transitively [the dynflow PR](https://github.com/Dynflow/dynflow/pull/214)

Fixes #18650 - Plan job executions in batches

---

app/views/job_invocations/_form.html.erb

It also fixes issue with keeping effective user value when the form is
re-rendered.

Fixes #17410 - effective user from job invocation on rerun

---

app/controllers/api/v2/job_invocations_controller.rb
app/controllers/concerns/foreman/controller/parameters/job_template.rb
app/lib/actions/remote_execution/run_host_job.rb
app/models/job_invocation_composer.rb
app/views/job_invocations/_form.html.erb
app/views/job_invocations/_tab_overview.html.erb
app/views/job_templates/_custom_tabs.html.erb
db/migrate/20170613101039_add_timeout_to_job_templates_and_job_invocations.rb
foreman_remote_execution_core.gemspec
lib/foreman_remote_execution_core/script_runner.rb

requires https://github.com/theforeman/foreman-tasks/pull/258

Fixes #20016 - Allow jobs to timeout

---

app/helpers/remote_execution_helper.rb
app/lib/actions/remote_execution/run_host_job.rb
foreman_remote_execution.gemspec

requires https://github.com/theforeman/foreman-tasks/pull/267

Fixes #19937 - Better job cancel handling

---

app/models/concerns/foreman_remote_execution/taxonomy_extensions.rb

Both the referenced issue and the PR were closed long time ago and I don't think we're supporting foreman 1.9 anymore.

Fixes #20427 - Compatibility fix for rails 5

---

foreman_remote_execution.gemspec
test/benchmark/run_hosts_job_benchmark.rb
test/benchmark/targeting_benchmark.rb
test/factories/foreman_remote_execution_factories.rb
test/functional/api/v2/foreign_input_sets_controller_test.rb
test/functional/api/v2/job_invocations_controller_test.rb
test/functional/api/v2/job_templates_controller_test.rb
test/functional/api/v2/remote_execution_features_controller_test.rb
test/functional/api/v2/template_inputs_controller_test.rb
test/test_plugin_helper.rb
test/unit/actions/run_hosts_job_test.rb
test/unit/concerns/foreman_tasks_cleaner_extensions_test.rb
test/unit/concerns/host_extensions_test.rb
test/unit/concerns/nic_extensions_test.rb
test/unit/input_template_renderer_test.rb
test/unit/job_invocation_composer_test.rb
test/unit/job_invocation_test.rb
test/unit/job_template_effective_user_test.rb
test/unit/job_template_importer_test.rb
test/unit/job_template_test.rb
test/unit/remote_execution_feature_test.rb
test/unit/remote_execution_provider_test.rb
test/unit/targeting_test.rb
test/unit/template_input_test.rb
test/unit/template_invocation_input_value_test.rb

FactoryGirl is now FactoryBot
factory_girl_rails is now factory_bot_rails
Requires theforeman/foreman#4935
Do not merge before Nov 1

Fixes #21460 - s/FactoryGirl/FactoryBot/g + rubocop

---

app/models/remote_execution_provider.rb
app/models/ssh_execution_provider.rb

This allows to reuse the effective_interfaces/effective_user methods in other provider implementations such as https://github.com/theforeman/foreman_ansible/commit/a5e0827bc3ec6c8ab82f968907857a15646305d5

Fixes #22350 - Make REX provider more generic

---

app/views/api/v2/job_templates/base.json.rabl

API consistency on attributes w.r.t BZ : 1539042

Fixes #22450 - add attributes to GET job_templates API

---

app/controllers/api/v2/job_invocations_controller.rb
app/controllers/job_invocations_controller.rb
app/helpers/remote_execution_helper.rb
app/models/job_invocation.rb
app/views/template_invocations/show.html.erb
config/routes.rb
lib/foreman_remote_execution/engine.rb
test/functional/api/v2/job_invocations_controller_test.rb

Fixes #20496 - Add API for canceling jobs

---

app/views/job_invocations/_form.html.erb

I wonder how it could have worked for me when I tested it.

Refs #22609 - rename the field

---

app/models/concerns/foreman_remote_execution/foreman_tasks_cleaner_extensions.rb
test/unit/concerns/foreman_tasks_cleaner_extensions_test.rb

This should also fix failing tests on sqlite

 Fixes #23042 - Use new cleaner helpers 

---

app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/models/setting/remote_execution.rb
lib/foreman_remote_execution/engine.rb

Requires https://github.com/Dynflow/dynflow/pull/277, https://github.com/theforeman/foreman-tasks/pull/319 and https://github.com/theforeman/foreman/pull/5320

Fixes #20661 - use separate queue for rex jobs

---

app/lib/actions/remote_execution/run_host_job.rb
app/models/host_status/execution_status.rb
lib/foreman_remote_execution_core/fake_script_runner.rb
test/unit/actions/run_host_job_test.rb

With this finalizing a job will also update the hosts execution status.

Fixes #22955 - Update host status on finalize

---

app/lib/actions/remote_execution/run_hosts_job.rb
foreman_remote_execution.gemspec

Fixes #22700 - Use TriggerRepeat hook

---

app/models/remote_execution_provider.rb
lib/foreman_remote_execution_core/script_runner.rb
test/unit/remote_execution_provider_test.rb

This PR depends on https://github.com/theforeman/foreman_remote_execution/pull/342

Fixes #19130 - dzdo support

---

foreman_remote_execution.gemspec
foreman_remote_execution_core.gemspec

Set the license in the gemspec

---

.rubocop.yml
db/seeds.d/70-job_templates.rb

1.18 blocker, core seeds all templates to all taxonomies too

Fixes #23891 - share all templates to all taxonomies

---

app/lib/actions/remote_execution/run_hosts_job.rb

Fixes #21668 - Resilience

---

app/lib/foreman_remote_execution/renderer/scope/input.rb
app/models/input_template_renderer.rb
app/models/template_input.rb
lib/foreman_remote_execution/engine.rb

This needs theforeman/foreman#5683.

fixes #24130 - use new rendering engine

---

app/views/templates/ssh/package_action.erb
app/views/templates/ssh/power_action.erb
app/views/templates/ssh/puppet_run_once.erb
app/views/templates/ssh/run_command.erb
app/views/templates/ssh/service_action.erb
scripts/sync_templates.sh

I fixed the script and resynced templates.

fixes #25000 - fix remote execution template sync

---

app/views/job_invocations/show.html.erb

Fixes #25499 - Adapt to breadcrumb changes in core

---

lib/foreman_remote_execution_core/script_runner.rb

This is never set and always 'nil'.

Remove references to @known_hosts_file

---

app/models/input_template_renderer.rb

After https://github.com/theforeman/foreman/commit/b58439fabbeac20b68902021fed366725c26dc92 was merged, we should also pass the source to the scope so snippets still work correctly.

refs #24130 - pass source to template scope

---

db/migrate/20190111153330_remove_remote_execution_without_proxy_setting.rb

We missed this change in the original PR.

Refs #24299 - migration to remove proxy-less setting

---

app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/models/remote_execution_provider.rb
app/models/ssh_execution_provider.rb
foreman_remote_execution.gemspec
foreman_remote_execution_core.gemspec
lib/foreman_remote_execution_core.rb
lib/foreman_remote_execution_core/actions.rb
lib/foreman_remote_execution_core/fake_script_runner.rb
lib/foreman_remote_execution_core/polling_script_runner.rb
lib/foreman_remote_execution_core/script_runner.rb

 Fixes #24138 - Trigger tasks in batches

---

app/models/concerns/foreman_remote_execution/foreman_tasks_cleaner_extensions.rb

fix for https://projects.theforeman.org/issues/27106

fixed #27106

---

db/seeds.d/100-assign_features_with_templates.rb
lib/foreman_remote_execution/engine.rb

includes https://github.com/theforeman/foreman_remote_execution/pull/407

Fixes #25991 - provide puppet run feature 

---

.babelrc
.eslintrc
package.json

tests and linting have been verified

Fixes #27486 - Add foreman-vendor

---

.eslintrc
package.json

i18n capabilities and jquery should be imported in react code, ie:
```js
import { translate as __ } from 'foremanReact/common/i18n`
import $ from 'jquery'
```

Fixes #27489 - remove global in eslint config

---

extra/cockpit/cockpit.conf.example
extra/cockpit/foreman-cockpit.service

Additional changes to support packaging/installer changes for https://github.com/mvollmer/foreman-cockpit/blob/master/README.md

Fixes #27465 - foreman-cockpit service related files

---

app/controllers/api/v2/job_invocations_controller.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/models/job_invocation_composer.rb
app/models/targeting.rb
app/views/api/v2/job_invocations/main.json.rabl
app/views/job_invocations/_card_target_hosts.html.erb
app/views/job_invocations/_form.html.erb
db/migrate/20180913101042_add_randomized_ordering_to_targeting.rb
test/factories/foreman_remote_execution_factories.rb
test/unit/targeting_test.rb

Fixes #24124 - Allow executing jobs on hosts in randomized order

---

app/controllers/api/v2/job_templates_controller.rb
app/views/api/v2/job_templates/main.json.rabl
lib/foreman_remote_execution/engine.rb
lib/foreman_remote_execution/version.rb

Requires https://github.com/theforeman/foreman/pull/7051.

Fixes #27976 - Add desc field to job templates

---

extra/cockpit/foreman-cockpit.service

Fixes #28072 - Expand the systemd unit

---

extra/cockpit/foreman-cockpit
extra/cockpit/foreman-cockpit.service

This cleans up environmental variables and also adds SELinux wrapper. Untested!

Refs #28072 - expand env and add SELinux wrapper

---

lib/foreman_remote_execution/engine.rb

Recent commit 2bf43ec changes the way how we register assets for precompilation.
Sadly, this change caused plugin:assets:precompile[$plugin] rake task to ignore
certain assets for remote execution by disabling automatic asset detection.
This commit keeps the automatic detection disabled, but registers a list of
assets which should be precompiled.

Fixes #28348 - Register assets for precompilation

---

app/views/job_invocations/_tab_hosts.html.erb

~~Would be perfect to have theforeman/foreman#7189 first, but this works without it.~~
Edit - it's a hard dependency now.

Fixes #28314 - fixes autocomplete_search

---

package.json

Fixes #28668 - support vendor v4

---

package.json

This should hopefully fix nightly since we have builder v4 in packaging :crossed_fingers:

Refs #28668 - upgrade tfm-builder to v4

---

package.json

It might be the reason https://github.com/theforeman/foreman-packaging/pull/4347 is failing.

Refs #28668 - remove tfm/env and use tfm/vendor >= 4

---

app/models/foreign_input_set.rb

(cherry picked from commit 82a92f6a7e5ba92ed852402a1e4c3622b51961c7)

Fixes #28647 - Validate metadata for foreign inputs

---

lib/foreman_remote_execution/engine.rb

PR is part of  [Add default descriptions to all roles added from plugins](https://projects.theforeman.org/issues/28936) task.

Fixes #28975 - Add description to plugin roles

---

app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/views/job_invocations/_form.html.erb

when batch triggering is enabled
requires:

Fixes #28616 - Pass needed option to fix concurrency control

---

app/models/job_invocation.rb
app/views/job_invocations/_card_user_input.html.erb
app/views/job_invocations/_user_input.html.erb

(cherry picked from commit 5de3d6f6bae2fec40d518b43d8f8c1d948dcb24a)

Fixes #29465 - hide hidden values in job invocation

---

app/controllers/api/v2/job_invocations_controller.rb
app/models/concerns/foreman_remote_execution/host_extensions.rb
app/views/api/v2/job_invocations/main.json.rabl

Hammer PR: https://github.com/theforeman/hammer_cli_foreman_remote_execution/pull/32

Fixes #29867 - API - Show job status for each host on JobInvocation detail

---

app/controllers/api/v2/job_invocations_controller.rb
app/views/api/v2/job_invocations/main.json.rabl

Updates from review in https://github.com/theforeman/hammer_cli_foreman_remote_execution/pull/32

Fixes #30212 - API::JobInvocations#show - change host_status param to boolean

---

app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/models/job_invocation.rb
app/models/job_invocation_composer.rb
app/models/remote_execution_provider.rb
app/models/setting/remote_execution.rb
app/models/ssh_execution_provider.rb
app/views/job_invocations/_form.html.erb
db/migrate/20200623073022_add_su_password_to_job_invocation.rb
db/migrate/20200623073022_rename_sudo_password_to_effective_user_password.rb
lib/foreman_remote_execution_core/script_runner.rb
test/unit/actions/run_host_job_test.rb
test/unit/actions/run_hosts_job_test.rb
test/unit/job_invocation_composer_test.rb
test/unit/remote_execution_provider_test.rb

This feature adds the ability to use effective user method "su" with password.

Fixes #30188 - Provide the ability to use su with password

---

app/views/api/v2/job_invocations/main.json.rabl
test/functional/api/v2/job_invocations_controller_test.rb

based on the solution here: https://github.com/nesquena/rabl/issues/166

Fixes #30628 - show empty hosts in job invocation api

---

webpack/react_app/components/TargetingHosts/TargetingHosts.js
webpack/react_app/components/TargetingHosts/TargetingHostsPage.js

Fix error messages in TargetingHosts component after merge: https://github.com/theforeman/foreman/commit/40c561889079bf1aef5fa5bdb8c7951571ef19b0

Fixes #30853 - TargetingHosts component - required props

---

app/models/job_invocation.rb

Fixes #30902 - Allow searching job invocations by id

---

app/controllers/ui_job_wizard_controller.rb
config/routes.rb
lib/foreman_remote_execution/engine.rb
test/functional/ui_job_wizard_controller_test.rb

instead of adding more functions to the job templates api, create a new controller for the UI needs

Fixes #31180 - create job wizard controller

---

app/models/job_invocation_composer.rb

Fixes #30933, #30935 - Type=search input fixes

---

app/lib/actions/remote_execution/run_host_job.rb
foreman_remote_execution.gemspec
lib/foreman_remote_execution/engine.rb

Fixes #31737 - Mark RunHostsJob as observable

---

lib/foreman_remote_execution_core.rb

Fixes #32219 - Check if SPDC settings are available

---

app/lib/foreman_remote_execution/renderer/scope/input.rb

Fixes [#32065](https://projects.theforeman.org/issues/32065)

Fixes #32065 - Undeclared :error_message instance field

---

app/helpers/remote_execution_helper.rb
app/models/job_invocation.rb
app/models/setting/remote_execution.rb
app/services/renderer_methods.rb
foreman_remote_execution.gemspec
lib/foreman_remote_execution/engine.rb
test/helpers/remote_execution_helper_test.rb
test/unit/job_invocation_report_template_test.rb

needs tasks PR: theforeman/foreman-tasks#490
template PR: theforeman/foreman#8178

fixes #15265 - making reporting of tasks

---

foreman_remote_execution_core.gemspec

This pr is rather simple, the real work will need to happen in packaging.

Fixes #27770 - Add support for ed25519 keys

---

app/lib/actions/remote_execution/run_host_job.rb
lib/foreman_remote_execution/engine.rb

One nitpick - I am hitting an issue with the new UI, when I try to add a new webhook on the new events, UI tells me Events cannot be blank. I will discuss with Oleh.

Fixes #32357 - integrate rex features with webhooks

---

app/graphql/types/job_invocation.rb
foreman_remote_execution.gemspec
lib/foreman_remote_execution/engine.rb
test/graphql/queries/job_invocation_query_test.rb
test/graphql/queries/job_invocations_query_test.rb

Needs https://github.com/theforeman/foreman-tasks/pull/634 as it references the types defined there.

Fixes #32721 - Add GraphQL queries for JobInvocations

---

app/views/templates/ssh/module_action.erb

Refs #33024 - Pass feature as a string

---

app/models/job_invocation.rb
app/views/dashboard/_latest-jobs.html.erb
lib/foreman_remote_execution/engine.rb

Adds widget for latest REX jobs.

Fixes #32676 - Add status of REX jobs on dashboard

---

app/models/job_invocation_composer.rb
test/functional/api/v2/job_invocations_controller_test.rb

Needs https://github.com/theforeman/foreman-tasks/pull/643

Fixes #33108 - Add start_at for job recurrence

---

app/controllers/api/v2/job_invocations_controller.rb
app/models/job_invocation_composer.rb

Add options for setting sudo password and ssh password when creating REX job using hammer

Fixes #33087 - Add password options to hammer REX job

---

app/controllers/ui_job_wizard_controller.rb
config/routes.rb
lib/foreman_remote_execution/engine.rb
webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/AdvancedFields/__tests__/__snapshots__/AdvancedFields.test.js.snap
webpack/JobWizard/steps/form/Formatter.js
webpack/JobWizard/steps/form/SearchSelect.js

Follow up for https://github.com/theforeman/foreman/pull/8600

 Fixes #32890 - job wizard add resource picker

---

webpack/react_app/components/RecentJobsCard/RecentJobsCard.js

to keep  the card layout consistent across multiple screen sizes

Fixes #33848 - add xl2 support for REX card in host details

---

webpack/JobWizard/steps/Schedule/RepeatWeek.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js

I forgot it when adding weekly repeat on

Fixes #33728 - Job wizard add "At" field for weekly repeat

---

webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/steps/Schedule/PurposeField.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js
webpack/JobWizard/steps/Schedule/index.js

Fixes #33814 - Job wizard add Purpose field

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/steps/HostsAndInputs/buildHostQuery.js
webpack/JobWizard/steps/HostsAndInputs/index.js
webpack/JobWizard/steps/ReviewDetails/index.js

Fixed #32520 - Add review details to job wizard

---

app/lib/actions/remote_execution/run_host_job.rb
app/models/concerns/foreman_remote_execution/host_extensions.rb
app/models/job_invocation_composer.rb
app/models/targeting.rb
lib/foreman_remote_execution/engine.rb
test/unit/actions/run_host_job_test.rb
test/unit/concerns/host_extensions_test.rb
test/unit/job_invocation_composer_test.rb
test/unit/targeting_test.rb

Part of https://community.theforeman.org/t/infrastructure-roles/22001

Fixes #32326 - Require additional permission to execute jobs against system hosts

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/steps/HostsAndInputs/buildHostQuery.js
webpack/JobWizard/steps/HostsAndInputs/index.js
webpack/JobWizard/submit.js

Fixes #33823 - job wizard submit data and create a job

---

webpack/JobWizard/steps/Schedule/StartEndDates.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js
webpack/JobWizard/steps/Schedule/__tests__/StartEndDates.test.js
webpack/JobWizard/steps/Schedule/index.js

Depends on https://github.com/theforeman/foreman_remote_execution/pull/666 just so this pr can add tests for both

Fixes #33820 - job wizard disable ends when no repeat

---

db/seeds.d/20-permissions.rb
lib/foreman_remote_execution/engine.rb

Requires:
- https://github.com/theforeman/foreman/pull/9064
- https://github.com/theforeman/foreman/pull/9073

Fixes #34324 - Exclude infra permission from default roles

---

jsconfig.json
package.json
webpack/global_index.js
webpack/react_app/components/FeaturesDropdown/actions.js
webpack/react_app/components/FeaturesDropdown/constant.js
webpack/react_app/components/FeaturesDropdown/index.js
webpack/react_app/components/RecentJobsCard/RecentJobsCard.js
webpack/react_app/components/RecentJobsCard/RecentJobsTable.js
webpack/react_app/components/RecentJobsCard/constants.js
webpack/react_app/extend/fillRexFeaturesDropdown.js

https://user-images.githubusercontent.com/11807069/149392178-43bb0abf-42da-4742-98e9-1a70c385bde3.mov

Fixes #34260 - add rex features dropdown to host page

---

app/models/concerns/foreman_remote_execution/host_extensions.rb
app/models/concerns/foreman_remote_execution/smart_proxy_extensions.rb
app/models/ssh_execution_provider.rb
app/services/default_proxy_proxy_selector.rb
app/services/remote_execution_proxy_selector.rb
db/seeds.d/60-ssh_proxy_feature.rb

This should go in before https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/77, once this is in, things should continue working no matter if the proxy has the newer bits or not.

Introduce Script proxy feature

---

lib/foreman_remote_execution/engine.rb
webpack/react_app/extend/fillRecentJobsCard.js

Taking over from https://github.com/theforeman/foreman_remote_execution/pull/697

Refs #34876 - Fix slot id for recent jobs card

---

app/models/remote_execution_feature.rb
lib/foreman_remote_execution/engine.rb
test/unit/job_invocation_report_template_test.rb
test/unit/job_invocation_test.rb

This will be required, once the https://github.com/theforeman/foreman/pull/9093 is merged.

Refs #34396 - reflect the report name change

---

app/controllers/foreman_remote_execution/concerns/api/v2/registration_commands_controller_extensions.rb
app/controllers/foreman_remote_execution/concerns/api/v2/registration_controller_extensions.rb
lib/foreman_remote_execution/engine.rb
webpack/react_app/components/RegistrationExtension/RexPull.js
webpack/react_app/extend/Fills.js

Requires:
- https://github.com/theforeman/foreman/pull/9235

Fixes #34970 - Allow enabling REX pull in registration form

---

webpack/react_app/extend/Fills.js

Requires https://github.com/theforeman/foreman/pull/9251
With all 4 changes applied, card order should be as illustrated there.

Fixes #35003 - Change recent jobs card weight

---

webpack/react_app/components/HostKebab/KebabItems.js
webpack/react_app/components/RecentJobsCard/RecentJobsCard.js
webpack/react_app/components/RecentJobsCard/RecentJobsTable.js

Per https://issues.redhat.com/browse/SAT-11706
Related to https://github.com/Katello/katello/pull/10249

Fixes #35426 - Add ouiaId prop to all supported components in host details

---

webpack/react_app/components/RecentJobsCard/RecentJobsTable.js

Its more correct to use table in this case and its easier for qe to test

Fixes #35437 - host details jobs change from list to table

---

app/models/job_invocation_composer.rb
app/models/remote_execution_provider.rb
app/views/job_invocations/_form.html.erb
db/migrate/20220822155946_add_time_to_pickup_to_job_invocation.rb
lib/foreman_remote_execution/engine.rb

overridable by the usual parameter hierarchy and per job.

Fixes #35408 - Add time_to_pickup setting

---

webpack/react_app/components/FeaturesDropdown/index.js

Followup of https://github.com/theforeman/foreman_remote_execution/pull/751

Refs #35426 - Add ouiaId to Schedule a job

---

app/controllers/job_templates_controller.rb

Replaced Foreman::Cast.to_bool with implementation from rails.

Fixes #35494 - Replace Foreman to_bool with rails implementation

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/steps/Schedule/ScheduleRecurring.js
webpack/JobWizard/submit.js

* send feature data on post
* use templateValues in advanced fields - already done in a different pr
* clean up unused css and typos

Fixes #35748 - job wizard code cleanup

---

lib/foreman_remote_execution/engine.rb
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/steps/AdvancedFields/__tests__/__snapshots__/AdvancedFields.test.js.snap
webpack/JobWizard/steps/HostsAndInputs/HostSearch.js
webpack/JobWizard/steps/HostsAndInputs/index.js
webpack/JobWizard/steps/form/Formatter.js

For when https://github.com/theforeman/foreman/pull/9277 breaks rex

Fixes #35828- remove search workarounds

---

webpack/JobWizard/steps/ReviewDetails/helpers.js
webpack/JobWizard/steps/ReviewDetails/index.js
webpack/JobWizard/steps/Schedule/RepeatWeek.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js

Fixes #36010 - add schedule info to review step in wizard

---

app/views/job_invocations/_form.html.erb
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/steps/HostsAndInputs/__tests__/HostsAndInputs.test.js
webpack/JobWizard/steps/Schedule/QueryType.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js

Category and Template -> Category and template (sentence case)
Planed -> planned

Fixes #36245 - fix typos (Template, planed)

---

app/controllers/ui_job_wizard_controller.rb

sorry :upside_down_face:
removes debugging leftovers from https://github.com/theforeman/foreman_remote_execution/pull/788

Fixes #36253 - delete 36096 leftovers in job_invocation

---

webpack/JobWizard/steps/Schedule/RepeatHour.js
webpack/JobWizard/steps/form/DateTimePicker.js
webpack/JobWizard/steps/form/GroupedSelectField.js
webpack/JobWizard/steps/form/SelectField.js

menuAppendTo was used before we fixed some z-index issues. it is not needed anymore.

Fixes #36240 - remove menuAppendTo

---

webpack/JobWizard/JobWizard.scss
webpack/JobWizard/steps/HostsAndInputs/SelectedChips.js
webpack/JobWizard/steps/HostsAndInputs/__tests__/HostsAndInputs.test.js

- visual improvement
- add close all chips per chip group x button
- added translation to the `x more` button here: collapsedText
before:
after:

Fixes #36247 - job wizard host chips improvement

---

webpack/react_app/components/RegistrationExtension/RexPull.js

This pr is in reference to foreman pr: https://github.com/theforeman/foreman/pull/9686

Fixes #36308 - Remove * for non required fields

---

webpack/JobWizard/JobWizardPageRerun.js

Requested by Maria from UXD
difference example (the second alert is inline)

Fixes #36246 - change org/location alert to be inline

---

app/views/job_invocations/_card_schedule.html.erb
lib/foreman_remote_execution/engine.rb
webpack/JobWizard/steps/AdvancedFields/Fields.js
webpack/JobWizard/steps/Schedule/RepeatCron.js

Fixes #36457, #36458 - wizard tooltip text and show Time to pickup in job details

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
webpack/JobWizard/steps/CategoryAndTemplate/index.js

Fixed the "ERF42-4237 [Foreman::Exception]: Unknown input command for template Install Package - Katello Script Default" error when customizing remote execution job.

Fixes #36633 - Fix "Unknown input command" error when submitting job

---

lib/foreman_remote_execution/engine.rb
webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/index.js

~draft until foreman uses the pf4 `Page` component~ - done

Fixes #36570 - pin wizard navigation to bottom

---

app/helpers/concerns/foreman_remote_execution/job_templates_extensions.rb
app/views/job_invocations/new.html.erb
app/views/job_invocations/welcome.html.erb

Found more places where the button was missing

Refs #36974 - show run job button to rex users

---

package.json

inspired by https://github.com/theforeman/foreman_ansible/commit/4fabaf9db9296c0dfcd84b575031018968d5ff2a

Open up @theforeman dependencies

---

app/models/concerns/foreman_remote_execution/host_extensions.rb

Companion to https://github.com/theforeman/foreman/pull/10136

Fixes #37373 - Expose execution interface in host jail

---

.github/workflows/release.yml

See https://github.com/theforeman/actions/pull/50

Fix the tags check for the release gem action

---

app/views/templates/script/convert2rhel_analyze.erb
lib/foreman_remote_execution/version.rb

Cherry-picks:
* 9343d7dc46a9a9276adaefccdbdcdb177557b31f
* 561f591b0e387528ca561c7a887401019f9ed1b6

Back-port Convert2RHEL flags to older releases

---

app/views/templates/script/package_action.erb

Small addition to https://github.com/theforeman/foreman_remote_execution/pull/881

Fixes #37492 - same response code for pkg removal

---

webpack/JobWizard/JobWizard.scss

so users will have more space to type in

Fixes #37557 - change job wizard width

---

app/views/templates/script/package_action.erb

Fixes #37545 - Fix package_action for dash

---

app/lib/actions/remote_execution/proxy_action.rb

when proxy callback does not go through

Fixes #37494 - Properly load proxy data

---

db/migrate/20240522093413_migrate_smart_proxy_ids_to_template_invocations.rb

Fixes #37922 - Handle case where proxy no longer exists

---

lib/foreman_remote_execution/engine.rb
lib/tasks/foreman_remote_execution_tasks.rake

Rebased on https://github.com/theforeman/foreman_remote_execution/pull/924

Fixes #37992 - User view_job_invocations permission for hosts action

---

foreman_remote_execution.gemspec

Ship tests in the gem

---

db/migrate/20240312133027_extend_template_invocation_events.rb

Fixes #38021 - Deal with duplicated exit events

---

app/views/api/v2/job_invocations/main.json.rabl
webpack/JobInvocationDetail/__tests__/fixtures.js
webpack/JobInvocationDetail/index.js

Fixed reporting of the job status should rely on the local browser time

Fixes #38258 - Fix resolved date of job invocation

---

webpack/JobWizard/steps/form/FormHelpers.js

Fixes: f0235ca3dc6645ee990c6799600fd69a2323f14b

Hardcode form group label help

---

webpack/JobInvocationDetail/TemplateInvocationComponents/OutputCodeBlock.js

auto scrolls to the bottom of the host job output once the input changes, only if the user is already at the bottom of the page, to avoid page jumps

Fixes #38184 - auto scroll to bottom job details

---

app/controllers/api/v2/job_templates_controller.rb
app/models/job_template.rb
test/functional/api/v2/job_templates_controller_test.rb

Refs #38527 - Duplicate associations on job template clone

---

webpack/JobInvocationDetail/index.js

The skeleton is not included in the description as it doesn't function as intended with the `<Head>`.

Sort out the loading of the new job invocation page
