theforeman/foreman_remote_execution

.rubocop.yml
app/helpers/remote_execution_helper.rb
app/models/concerns/foreman_remote_execution/template_extensions.rb
app/models/concerns/foreman_remote_execution/template_relations.rb
app/models/input_template_renderer.rb
app/models/template_input.rb
lib/foreman_remote_execution/engine.rb
test/factories/foreman_remote_execution_factories.rb
test/unit/input_template_renderer_test.rb

This PR adds InputTemplateRenderer object which can render a template
that contains input("name") macros. It also allows previewing of such
templates which expands macros to placeholders if values are not ready
yet. Currently it supports fact, variable and puppet parameter input
types, user type is ready but can be implemented once we have job
invocation objects in place.

Rendering templates with inputs

---

lib/foreman_remote_execution/engine.rb
lib/foreman_remote_execution/version.rb

We need to explicitly force to load the Task model due to Rails loader having
issues with resolving it to Rake::Task otherwise

Fix random loading issues when extending ForemanTasks::Task model

---

.gitignore
app/models/job_template.rb
app/models/template_input.rb
app/models/template_invocation_input_value.rb
app/views/job_invocations/_form.html.erb
app/views/template_inputs/_form.html.erb
app/views/templates/package_action.erb
app/views/templates/puppet_run_once.erb
app/views/templates/run_command.erb
app/views/templates/service_action.erb
db/migrate/20150827152730_add_options_to_template_input.rb
db/seeds.d/70-job_templates.rb
test/unit/input_template_renderer_test.rb
test/unit/job_template_test.rb
test/unit/template_invocation_input_value_test.rb

Provides:
- Package Action
- Puppet Run Once
- Run Command
- Service Action
Templates are seeded by YAML, essentially  a cleaned up `template.to_json(:includes => :template_inputs)`.  We could also go the Foreman route and put the metadata in an ERB comment at the top.
I add a new `select_options` input type, I wanted this for the package action where a user could select from install/update/etc. 
Here's a gif if you just want to see:

fixes #11469 - Ship some default templates

---

app/views/template_inputs/_form.html.erb

The input type has a limited number of options and the select2 was causing
issues with dynamically generated fields.

Fixes #11722 - disable select2 on input_type

---

app/views/job_templates/index.html.erb
test/unit/input_template_renderer_test.rb

include_javascript is not needed (and present) anymore, and lookup keys
factories changed behavior and we need to use some specialized factories.

Fixes #11759 - fix include_javascript and lookup keys preparation

---

app/models/concerns/foreman_remote_execution/taxonomy_extensions.rb

Otherwise we hit issues described in rails/rails#12180 (comment), will not be
needed once https://github.com/theforeman/foreman/pull/2723 is in and we don't
support older versions

Refs #11805 - use before_create instead of after_create for default templates

---

.rubocop.yml
app/assets/javascripts/execution_interface.js
app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/models/concerns/foreman_remote_execution/host_extensions.rb
app/models/concerns/foreman_remote_execution/nic_extensions.rb
app/models/concerns/foreman_remote_execution/subnet_extensions.rb
app/models/job_invocation.rb
app/models/setting/remote_execution.rb
app/models/target_remote_execution_proxy.rb
app/overrides/execution_interface.rb
app/overrides/foreman/nics/_execution_interface.html.erb
app/overrides/foreman/subnets/_rex_tab.html.erb
app/overrides/foreman/subnets/_rex_tab_pane.html.erb
app/overrides/subnet_proxies.rb
app/services/proxy_load_balancer.rb
db/migrate/20150826191632_create_target_remote_execution_proxies.rb
db/migrate/20150903192731_add_execution_to_interface.rb
foreman_remote_execution.gemspec
lib/foreman_remote_execution.rb
lib/foreman_remote_execution/engine.rb
test/factories/foreman_remote_execution_factories.rb
test/test_plugin_helper.rb
test/unit/actions/run_hosts_job_test.rb
test/unit/actions/run_proxy_command_test.rb
test/unit/concerns/host_extensions_test.rb
test/unit/concerns/nic_extensions_test.rb
test/unit/proxy_load_balancer_test.rb

Currently, when you schedule an action, we determine the proxy to handle the request by some magic, in the following order:
1. We look at all the proxies attached to the host (Puppet, TFTP, DNS) and see if any have remote execution features we're looking for.  We take the first we find.
1. If you enable the setting `remote_execution_global_proxy`, and we don't find a proxy on the Host, we'll expand our search to all proxies.
1. If nothing is found, fail for that host.
This works, but we need some more granular control over this in order to be deterministic in the proxies we choose in multi-proxy environments, and account for complex networking setups. We want to do it without making the user's life too difficult. 
This PR adds the concept of an "Execution Interface."  New hosts will …

fixes #11554, #11827 - execution proxy through subnet, with load balancing

---

app/assets/javascripts/template_invocation.js

Foreman 1.9 didn't include underscore.js, but we are ok with jQuery in this
case.

Refs #12065 - fix foreman 1.9 compatibility with refresh js

---

foreman_remote_execution.gemspec

fixes #24
`git ls-files` seems to be somewhat controversial based on Googling, but it works fine and ensures only committed files get released.

fixes #12125 - use git ls-files in gemspec

---

app/models/concerns/foreman_remote_execution/host_extensions.rb

Without the patch, discovery reboot fails on
``` NoMethodError: undefined method `drop_execution_interface_cache' for
```

Fixes #12233 - clean the interface cache only when becoming Managed::Host

---

app/models/job_template.rb
test/unit/job_template_test.rb

**Problem**
You can create job templates without a job_name currently. This leads to a situation where you cannot use the template in a job invocation because it lacks a job_name. 
**Solution**
Validate that the job_name is present on save on every job template creation.

Fixes #12246 - Validate job_name on template creation

---

app/models/setting/remote_execution.rb

With this as a default, then the plugin just works out of the box.  More
advanced users will likely want to turn it off and use subnet-based
proxy determination for segmented networks while getting proper HA, load
balancing, etc.

fixes #12316 - make global proxy turned on by default

---

README.md

**Problem**
People come to the repo and don't know how to install the project,
what does it exactly do, etc.. People ask in #theforeman IRC channel
about basic help on how to install the plugin because they didn't
see any documentation in the README.
**Solution**
Add a few basic information screenshots, points of contact, and links
to the manual to ensure new users don't get lost.

Update README to include features, link to manual

---

app/lib/proxy_api/remote_execution_ssh.rb
app/models/concerns/foreman_remote_execution/host_extensions.rb
app/models/concerns/foreman_remote_execution/smart_proxy_extensions.rb
app/views/unattended/snippets/_remote_execution_ssh_keys.erb
db/migrate/20151013135415_add_pub_key_to_smart_proxy.rb
db/seeds.d/80-provision_templates.rb
lib/foreman_remote_execution/engine.rb
test/unit/concerns/host_extensions_test.rb

Includes a snippet to deploy the ssh keys to a host for all the relevant proxies.  You'll need to include
`<%= snippet 'remote_execution_ssh_keys' %>` 
in the %post of your provision template, or in the finish/userdata templates, and they'll automatically be setup for the authorized_keys.
The ssh keys are also included in the global parameters, so changes can be managed with a potential puppet module.  Should we provide one?
Also, this is based on how things currently are, we still need to have some discussion/planning about what more advanced use cases we need to support.

refs #11633 - template support for deploying ssh keys

---

app/views/job_invocations/new.html.erb

**Problem**
When you click on 'Run Job' on a host, there is no title on that page.
**Solution**
Add a title to the new page for Job invocations.

Fixes #12317 - Missing title on new job invocation

---

app/lib/actions/remote_execution/run_host_job.rb
app/models/concerns/foreman_remote_execution/host_extensions.rb
app/models/setting/remote_execution.rb
test/unit/concerns/host_extensions_test.rb

Greatly simplified after discussing with @iNecas  this morning:
- Global setting `remote_execution_ssh_user` is used by default
- Parameter of same name can be set to allow customization - let user set user names as granularly as they want by using parameter hierarchy: per host, per host group, environment, etc.
Accompanies https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/10

fixes #11634 - allow customization of ssh user

---

app/models/job_invocation_composer.rb
test/unit/job_invocation_composer_test.rb

Otherwise when there's no query, it shows you all hosts

fixes #12407 - show 0 hosts in count and preview when there's no query

---

app/lib/actions/remote_execution/helpers/live_output.rb
app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_proxy_command.rb

Don't raise cryptic errors when there is no reasonable output comming from the
proxy.
Also, improve the error message a proxy in missing (and proxy command fails in planning
phase). There is still work to be done to get to the erors from the job hosts list,
but this requires some changes on dynflow side that I don't want to rush to get
into stable relese. But at least, when going to the `Monitor -> Tasks` and showing
the failed `RuhHostJob` task, one doesn't see:
undefined method `live_output' for nil:NilClass (NoMethodError)

Fixes #12437, refs #12288 - better handling of unexpected states

---

app/assets/javascripts/template_invocation.js
app/controllers/job_invocations_controller.rb
app/helpers/remote_execution_helper.rb
app/lib/actions/middleware/bind_job_invocation.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/models/concerns/foreman_remote_execution/foreman_tasks_task_extensions.rb
app/models/concerns/foreman_remote_execution/foreman_tasks_triggering_extensions.rb
app/models/job_invocation.rb
app/models/job_invocation_composer.rb
app/models/job_invocation_task_group.rb
app/models/targeting.rb
app/models/template_invocation.rb
app/views/api/v2/job_invocations/show.json.rabl
app/views/job_invocation_task_groups/_job_invocation_task_group.html.erb
app/views/job_invocation_task_groups/_job_invocation_task_groups.html.erb
app/views/job_invocations/_form.html.erb
app/views/job_invocations/show.html.erb
app/views/job_invocations/show.js.erb
db/migrate/20150923125825_add_job_invocation_task_group.rb
db/migrate/20151022105508_rename_last_task_id_column.rb
db/migrate/20151116105412_add_triggering_to_job_invocation.rb
test/unit/actions/run_hosts_job_test.rb
test/unit/job_invocation_test.rb

requires theforeman/foreman-tasks#141

Refs #10755 - Recurring actions, job invocation task groups

---

app/controllers/job_invocations_controller.rb
app/helpers/remote_execution_helper.rb
app/models/job_invocation.rb
app/views/job_invocations/index.html.erb

#44 broke jobs index and maybe something more because of renaming `last_task_id` column on `job_invocations` table to `task_id`.

Fixes unknown column errors on last_task

---

app/lib/actions/remote_execution/run_host_job.rb
foreman_remote_execution.gemspec

Otherwise we lose the link from the task to the job invocation. Since
in this case, the execution plan is not driving a transaction between
local database and external systems, we can turn this logic off for
this action.
With this patch (that depends on https://github.com/Dynflow/dynflow/pull/174),
when there is an issue with running the job on proxy (as in case when the proxy
is just down), we show the tasks on per-host part as failed, with posibility to
show details, as with any other error.

Fixes #12288 - disable transactions for plan phase in run host job action

---

app/views/job_invocations/refresh.js.erb

Use `replaceWith` instead of `html` for updating the form data
and re-initiate the bootstrap `popup` to fix the inline help.

Fixes #12769 - fix ajax refresh of invocation form

---

foreman_remote_execution.gemspec

There were some changes since 0.7.6 that are required by the recurring logic
so we should make sure we have the latest version available.

Refs #10753 - update foreman-tasks to 0.7.8

---

app/controllers/template_invocations_controller.rb
app/lib/actions/remote_execution/run_host_job.rb
app/models/template_invocation.rb
config/routes.rb
db/migrate/20151215114631_add_host_id_to_template_invocation.rb
lib/foreman_remote_execution/engine.rb

There are couple of things that has to be solved
* we have to link host of template_invocation somehow
* autocompletion in filters does not work, didn't have time to find why the path is wrong
* if the execution fails we don't display any nice message, in RunHostsJob we just know that sub task failed

Fixes #10758 - allow execution limiting by permissions

---

app/helpers/remote_execution_helper.rb
app/views/job_invocations/_host_actions_td.html.erb
app/views/job_invocations/_tab_hosts.html.erb
app/views/job_invocations/show.js.erb

based on https://github.com/theforeman/foreman_remote_execution/pull/92 to avoid conflicts, please review just the second commit or ideally review the second PR first...

Fixes #12926 - add rerun to host row in job detail

---

app/lib/actions/remote_execution/run_proxy_command.rb

The problem here is `task.ended_at` is according to the Foreman server's time, whereas other output lines happen in respect to the proxy's.  In my case, the two servers were several seconds off, causing "Exit status" to render in the middle of the output:
The simplicity of sorting by time though is nice, so just put exit status at  Sat, 20 Nov 2286 17:46:39 GMT, a.k.a 9999999999 seconds from the epoch.
Any other suggestions to handle this?

fixes #12753 - exit status should be last item

---

app/models/job_invocation.rb

Otherwise, the scoped search has issues producing valid sql

Fixes #13011 - use standard way to join with task

---

app/views/unattended/snippets/_remote_execution_ssh_keys.erb

Reported on IRC by a user.  present? not allowed in safemode on Array. I thought I tested this with safemode enabled, but guess not.  stbenjam--

fixes #13088 - use !blank? instead of present? in ssh key snippet

---

app/helpers/remote_execution_helper.rb
app/views/job_templates/index.html.erb

As the rest of Foreman, this plugin can benefit from links to the
documentation straight from the app. Two easy places to start are the
job invocations/ job templates indexes.

Fixes #13173 - Documentation button links for job invocations/templates

---

app/controllers/job_invocations_controller.rb
app/controllers/template_invocations_controller.rb
app/helpers/remote_execution_helper.rb
app/lib/actions/middleware/bind_job_invocation.rb
app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/models/job_invocation.rb
app/models/job_invocation_composer.rb
app/models/job_template.rb
app/models/template_invocation.rb
app/views/job_invocations/_host_actions_td.html.erb
app/views/job_invocations/_host_name_td.html.erb
app/views/job_invocations/_tab_hosts.html.erb
app/views/job_invocations/_tab_overview.html.erb
app/views/job_invocations/show.js.erb
app/views/template_invocations/show.html.erb
db/migrate/20160113161916_add_run_host_job_task_id_to_template_invocation.rb
db/migrate/20160113162007_expand_all_template_invocations.rb
test/factories/foreman_remote_execution_factories.rb
test/unit/actions/run_hosts_job_test.rb
test/unit/job_invocation_composer_test.rb
test/unit/job_invocation_test.rb
test/unit/job_template_test.rb
test/unit/remote_execution_provider_test.rb

This commit introduces so called pattern template invocation which is
created by job composer as a pattern for real template invocation that
being created during dynflow action run. Pattern template invocation
holds all information from composer (e.g. input values) except target
host which is evaluated just during dynflow action run phase.

Fixes #13130 - save template invocations for each host

---

app/lib/actions/middleware/bind_job_invocation.rb

There's a debate about calling these method names correctly, and splitting deep_clone (no save) with deep_clone! which saves, but @ares will file a separate issue to make this consistent.

fixes #13308 - call correct method on job invocation

---

app/models/template_invocation.rb

this is needed for execute permission filters, we used to use job_name for that

Fixes #13312 - enable filtering on template name

---

app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb

Requires https://github.com/theforeman/foreman/pull/2892

[Foreman 1.11] fixes #12312 - bulk actions opens job invocation in new page directly

---

app/overrides/foreman/nics/_execution_interface.html.erb

Notice the label change to 'Remote execution', which I think it's more
clear. I also changed the help inline to a popover as per Patternfly
guidelines https://www.patternfly.org/patterns/field-level-help/
before: ![](http://i.imgur.com/pzoelrF.png)
after: ![](http://i.imgur.com/IDZiBk5.png)

Fixes #13342 - Align Remote execution checkbox in NICs modal

---

app/views/job_invocations/index.html.erb
app/views/job_templates/index.html.erb

before
after
and similarly for job invocations

Fixes #13137 - Improve table styles

---

app/assets/javascripts/template_invocation.js
app/controllers/api/v2/template_inputs_controller.rb
app/helpers/remote_execution_helper.rb
app/models/template_input.rb
app/views/job_invocations/_form.html.erb
app/views/template_inputs/_form.html.erb
app/views/template_inputs/_invocation_form.html.erb
app/views/templates/package_action.erb
db/migrate/20160127134031_add_advanced_to_template_input.rb

RFC, I'm not sure if some icon next to link would help or maybe move schedule selection above inputs?

Fixes #13142 - introduce advanced flag

---

app/assets/stylesheets/template_invocation.css.scss

The CSS on that page makes the SSH output very difficult to read.
See a couple of examples:
The CSS from the foreman-docker console output seems a lot more
readable, see how it would look like in this plugin:

Fixes #13334 - Job live output is very hard to read

---

app/models/input_template_renderer.rb
app/views/templates/package_action.erb

This change renames the 'die' function to 'exit_with_message' as some
users found it particularly terrifying to see this as the first line in
the template preview. It also adds documentation to the function.
We can extract this to a helper snippet later if we have more or it
becomes useful elsewhere.
Secondly, it causes the package action template to fail more gracefully
when a host has no operating system, or an unsupported one.

fixes #13133, #13632 - improve package action template

---

app/controllers/api/v2/job_invocations_controller.rb
app/controllers/job_invocations_controller.rb
app/lib/actions/remote_execution/run_hosts_job.rb
app/models/job_invocation_composer.rb
app/views/job_invocations/_form.html.erb
db/migrate/20160203104056_add_concurrency_options_to_job_invocation.rb
foreman_remote_execution.gemspec
test/unit/actions/run_hosts_job_test.rb
test/unit/job_invocation_composer_test.rb

Allows to limit concurrency level or distribute sub tasks over the provided time window (or both).
Quick overview:
- all sub plans get planned immediately, their `run` phases get held back until it is possible to start them without breaking the limits
- sub plans which are not started within the time window are cancelled
- sub plans which fail in the plan phase ignore the limits and are finished immediately
Requires Dynflow/dynflow/pull/179

Fixes #10751 - Support for concurrency control

---

app/models/concerns/foreman_remote_execution/host_extensions.rb
test/unit/concerns/host_extensions_test.rb

The user is not set in context of provisioning, therefore the public
keys of the global proxies were not populated properly into the provisioned
hosts.

Fixes #13689 - don't use authorized scope in provisioning template

---

app/models/job_template.rb
app/models/setting/remote_execution.rb
db/seeds.d/70-job_templates.rb
test/unit/job_template_test.rb

This syncs job templates during `db:seed` (and bypasses the foreman idempotency check here only), so they're always up to date without needing to create individual migrations.
These sync methods will also be able to be used to add support for syncing job templates from git using the foreman_templates plugin.

fixes #13579 - sync templates during seed

---

app/controllers/api/v2/job_invocations_controller.rb
app/controllers/api/v2/remote_execution_features_controller.rb
app/controllers/job_invocations_controller.rb
app/controllers/remote_execution_features_controller.rb
app/helpers/remote_execution_helper.rb
app/lib/actions/remote_execution/run_host_job.rb
app/models/job_invocation.rb
app/models/job_invocation_composer.rb
app/models/job_template.rb
app/models/job_template_effective_user.rb
app/models/remote_execution_feature.rb
app/models/targeting.rb
app/views/api/v2/remote_execution_features/base.json.rabl
app/views/api/v2/remote_execution_features/index.json.rabl
app/views/api/v2/remote_execution_features/main.json.rabl
app/views/api/v2/remote_execution_features/show.json.rabl
app/views/job_invocations/_form.html.erb
app/views/remote_execution_features/_form.html.erb
app/views/remote_execution_features/index.html.erb
app/views/remote_execution_features/show.html.erb
app/views/templates/package_action.erb
config/routes.rb
db/migrate/20160118124600_create_remote_execution_features.rb
lib/foreman_remote_execution/engine.rb
test/functional/api/v2/remote_execution_features_controller_test.rb
test/unit/job_template_test.rb
test/unit/remote_execution_feature_test.rb
test/unit/targeting_test.rb

Depends on https://github.com/theforeman/foreman_remote_execution/pull/148
opening separate PR for discussing the katello-related issues. The general developer API comments should go to https://github.com/theforeman/foreman_remote_execution/pull/148.

Fixes #10757 - preparation for Katello remote actions integration

---

app/helpers/remote_execution_helper.rb

Old: can't figure out how many tasks are actually running when using concurrency control
New:

Fixes #13786 - Distinguish between planned and running

---

app/helpers/remote_execution_helper.rb

Currently it shows the provider class name, which the user doesn't need
to know about.
Before:
After:

Fixes #13839 - Show provider humanized name on job templates form

---

app/assets/javascripts/job_templates.js
app/assets/stylesheets/modal_window.css.scss
app/controllers/api/v2/job_templates_controller.rb
app/controllers/job_templates_controller.rb
app/helpers/concerns/foreman_remote_execution/job_templates_extensions.rb
app/models/concerns/foreman_remote_execution/exportable.rb
app/models/foreign_input_set.rb
app/models/job_template.rb
app/models/template_input.rb
app/views/job_invocations/_preview_hosts_modal.html.erb
app/views/job_templates/_import_job_template_modal.html.erb
app/views/job_templates/index.html.erb
config/routes.rb
lib/foreman_remote_execution/engine.rb
test/functional/api/v2/job_templates_controller_test.rb
test/unit/concerns/exportable_test.rb
test/unit/job_template_test.rb
test/unit/template_input_test.rb

This lets you export the template in our import format (metadata in a YAML comment).  The idea here is to facilitate easier sharing / creation of new templates, moving us a step closer to creating a vibrant community of job templates in the community-templates repo.

fixes #13922 - import/export job templates with metadata

---

app/models/remote_execution_feature.rb
db/migrate/20150612121541_add_job_template_to_template.rb
db/migrate/20150616080015_create_template_input.rb
db/migrate/20150708133241_add_targeting.rb
db/migrate/20150708133242_add_invocation.rb
db/migrate/20150708133305_add_template_invocation.rb
db/migrate/20150812145900_add_last_task_id_to_job_invocation.rb
db/migrate/20150826191632_create_target_remote_execution_proxies.rb
db/migrate/20151120171100_add_effective_user_to_template_invocation.rb
db/migrate/20151124162300_create_job_template_effective_users.rb
db/migrate/20151203100824_add_description_to_job_invocation.rb
db/migrate/20160108141144_make_job_name_default_to_something.rb
db/migrate/20160113161916_add_run_host_job_task_id_to_template_invocation.rb
db/migrate/20160118124600_create_remote_execution_features.rb
lib/tasks/foreman_remote_execution_tasks.rake
test/factories/foreman_remote_execution_factories.rb
test/test_plugin_helper.rb
test/unit/execution_task_status_mapper_test.rb

This should be compatible with Foreman 1.11 as well, so I'm not setting 1.12 flag.

WIP Fixing tests

---

app/models/remote_execution_feature.rb
db/migrate/20150612121541_add_job_template_to_template.rb
db/migrate/20150616080015_create_template_input.rb
db/migrate/20150708133241_add_targeting.rb
db/migrate/20150708133242_add_invocation.rb
db/migrate/20150708133305_add_template_invocation.rb
db/migrate/20150812145900_add_last_task_id_to_job_invocation.rb
db/migrate/20150826191632_create_target_remote_execution_proxies.rb
db/migrate/20151120171100_add_effective_user_to_template_invocation.rb
db/migrate/20151124162300_create_job_template_effective_users.rb
db/migrate/20151203100824_add_description_to_job_invocation.rb
db/migrate/20160108141144_make_job_name_default_to_something.rb
db/migrate/20160113161916_add_run_host_job_task_id_to_template_invocation.rb
db/migrate/20160118124600_create_remote_execution_features.rb
lib/tasks/foreman_remote_execution_tasks.rake
test/factories/foreman_remote_execution_factories.rb
test/test_plugin_helper.rb
test/unit/execution_task_status_mapper_test.rb

Looks like we actually need the rails 4.2 fixes in 0.3-stable branch, because it fixed some other bugs (validates vs. validate, duplicate indexes, etc).  But not all of them, this excludes the `:subnet_v4` change since it doesn't exist in 1.10.

Cherry-picks for 0.3.2

---

test/unit/remote_execution_feature_test.rb

On remote_execution_feature, there's a line calling `validate` and then
calls some Rails validations. It has a typo and should say `validates`.
Passenger does not start because of this, with an error
' Message from application: Unknown key: :presence. Valid keys are: :on,
:if, :unless, :prepend. Perhaps you meant to call `validates` instead
of `validate`? (ArgumentError) '
Fix is as simple as correcting the typo.

Refs #14842 - 'validate' should be 'validates'

---

app/models/job_invocation_composer.rb

Fixes #14684 - Save end time for recurring

---

app/models/job_template_effective_user.rb

Otherwise creating a new template fails with a
ForbiddenAttributesError.  Rails 4.2 must go
deeper in verifying attribute accessibility.

fixes #14847 - attr_accessible on effective user

---

app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb
app/helpers/remote_execution_helper.rb
app/views/job_templates/index.html.erb

Button links are broken in a few places due to https://groups.google.com/forum/#!topic/foreman-dev/QB9ZeK_m0Qw.
Foreman now provides a new_link helper for creating new objects. We need to use
that on the Job Templates and Invocations pages.  Additionally, other places
like Host "Run Job", we need to explicitly set the btn btn-default CSS.

fixes #14506 - use new_link helpers, and use button css

---

app/models/job_template.rb
test/factories/foreman_remote_execution_factories.rb
test/unit/job_template_test.rb

Setting the template on the feature instead of the feature on the
template causes the cascade save in Rails to not save it.

fixes #15017 - trigger save correctly with feature

---

app/models/setting/remote_execution.rb

Requires theforeman/foreman@ad603e4

fixes #15179 - Select box for settings

---

app/views/overrides/subnets/_rex_tab_pane.html.erb

Rails 5 will remove the option of passing nested arrays that are used in SQL 'IN' conditions. You can see several warnings running test/functional/subnets_controller.rb

Fixes #15667 - Passing nested array in smart-proxy scope is deprecated

---

app/views/api/v2/job_invocations/base.json.rabl

This fixes the regression introduce by
http://projects.theforeman.org/issues/15778, as the output
of the API for job-invocation show changed.

Fixes #16067 - state the API key for dynflow_task explicitly

---

app/models/job_template_importer.rb
test/unit/job_template_importer_test.rb

This is pretty much verbatim copy from the `update_job_template` method already present in foreman_templates itself. The only difference is that it deletes `model` from the metadata before passing it on to the real import call.
Not quite sure if tests are wanted / best place to implement them, guidance welcome.

Fixes #16426 - Add JobTemplateImporter shim class for foreman_templates

---

app/models/targeting.rb
test/benchmark/run_hosts_job_benchmark.rb
test/benchmark/targeting_benchmark.rb

Task queries were optimized for not bringing too much unneeded
objects. For more optimizations a proper performance analysis
is needed

Fixes #17921 - optimized task queries

---

lib/foreman_remote_execution_core/script_runner.rb

Alternative to #216
Instead of using SCP to copy the script we open an ssh connection and write the script into its stdin. On the other side of the tunnel we use `tee` to read from the stdin and write it to a file and `chmod` to set the permissions on the script.

 Fixes #17315 - Handle output coming from .bashrc, v2

---

app/models/job_invocation.rb
test/unit/job_invocation_test.rb

Previous algorithm failed, when the order of inputs was different than
the order of values in the invocation - the new test were extended with
and example that failed before this patch

Fixes #18298 - fix description generation

---

config/routes.rb
lib/foreman_remote_execution/engine.rb

We originally remove that due to permissions check, but
the proper fix is to keep it there.

Refs #18098 - keep the export in routes

---

app/models/concerns/foreman_remote_execution/host_extensions.rb
test/factories/foreman_remote_execution_factories.rb
test/functional/api/v2/job_templates_controller_test.rb
test/unit/concerns/host_extensions_test.rb

After the patch for the CVE in #16982, some tests fail in REX. This
fixes parts of REX where 'no taxonomies' implied 'all taxonomies'

Fixes #17976 - Fix tests for CVE 2016-7078

---

README.md
lib/foreman_remote_execution_core.rb
lib/foreman_remote_execution_core/actions.rb
lib/foreman_remote_execution_core/fake_script_runner.rb

This commit adds an alternative implementation for the ScriptRunner
class. Instead of doing ssh connections it discards any input its
given and gives back fake output.
It is controlled by setting the following environment variables
- ~~`REX_DEBUG`~~ `REX_SIMULATE` - setting to `1`, `yes` or `true` enables the use of the fake runner
- ~~`REX_DEBUG_PATH`~~ `REX_SIMULATE_PATH` - full path to a file which should be given back as output by the runner, currently one line per runner's refresh
- ~~`REX_DEBUG_FAIL_CHANCE`~~ `REX_SIMULATE_FAIL_CHANCE` - number from 0 to 100, each host has a ~~`REX_DEBUG_FAIL_CHANCE`~~ `REX_SIMULATE_FAIL_CHANCE` of exiting with ~~`REX_DEBUG_EXIT`~~ `REX_SIMULATE_EXIT`, useful for simulating random failures
- ~~`REX_DEBUG_EXIT`~~ `REX_SIMULATE_EXIT` - see the …

Fixes #18651 - Provide a way to test REX at scale

---

app/assets/javascripts/template_invocation.js

The issue was `modal_window` was set to `$('#previewHostsModal')` and later when changed didn't actually change `$('#previewHostsModal')`.
I couldn't find out why clicking the refresh button fixed this but setting `modal_window` only before using it fixed the issue.
Also, @matanwerbner advised to change `success` to `then` as `success` is deprecated and combine the `success` and `complete` parts since we did not have a different behavior for error and always tried to show the modal.

Fixes #17412 - Preview in job invocation works without refresh

---

lib/foreman_remote_execution/engine.rb

Please consider merging this before another release. This is new plugin DSL introduced in 1.15 that adds all permissions to Manager role and all view_* permissions to Viewer core roles.

Fixes #17953 - extend core roles with permissions

---

app/models/targeting.rb
test/test_plugin_helper.rb
test/unit/remote_execution_feature_test.rb
test/unit/targeting_test.rb

When asking to target a specific set of hosts (like in case of failed hosts), a `name = X or name = Y...` query was generated. This query caused a very deep stack recursion in scoped_search AST. This commit changes the query to `name ^ (X, Y...)` that will not require the same treatment in AST.

Fixes #18316 - Changed scoped_search query to :in for hosts enum

---

test/unit/job_invocation_composer_test.rb
test/unit/job_template_importer_test.rb

A change in Foreman's #19463 revealed an issue in remote execution
where we were not saving the user properly when testing permissions.
When auditing was present, it ensured the user was saved, while without
it, the saving of test user fails on password validation.
This commit uses Foreman's helper method to prepare the test user
which has the user preparation set properly.

Fixes #19525 - fix user reparation in tests

---

lib/foreman_remote_execution_core/script_runner.rb

- `tcsh` doesn't have `$(command)`
- `csh` doesn't have `$(command)` and apparently `$?`

Fixes #19401 - Compatibility fix for t?csh

---

lib/foreman_remote_execution_core/script_runner.rb

For the infrastructure files, we use the remote user: the effective
user is for the scope of the actual script

Fixes #19575 - don't use sudo prefix for script preparation

---

lib/foreman_remote_execution_core/script_runner.rb

Let's override the default locale with `C.UTF-8`. Users wanting to use their own locales can set them in their scripts, as long as the encoding is `UTF-8`.
Requires https://github.com/theforeman/foreman-tasks/pull/254

Fixes #18356 - Ensure UTF-8 encoding

---

app/models/template_input.rb
test/unit/input_template_renderer_test.rb

It keeps backward compatibility with Foreman 1.15.
While searching for older version compatibility checks, I've removed
really old ones.

Fixes #20101 - update input template renderer for Foreman 1.16

---

app/models/setting/remote_execution.rb
app/models/ssh_execution_provider.rb
foreman_remote_execution_core.gemspec
lib/foreman_remote_execution_core.rb
lib/foreman_remote_execution_core/script_runner.rb

For now it requires `net-ssh-krb` to be required into the `smart-proxy` or `smart_proxy_dynflow_core`
Packaging PRs:
- [DEB](https://github.com/theforeman/foreman-packaging/pull/1664)
- [RPM](https://github.com/theforeman/foreman-packaging/pull/1665)

Fixes #11936 - Allow authenticating with kerberos

---

app/controllers/api/v2/job_invocations_controller.rb

It will fail if the user has filters defined in roles.

Fixes #19936 - Don't call Host::Base.authorized

---

app/lib/actions/remote_execution/run_hosts_job.rb
foreman_remote_execution.gemspec

The default poll interval set in Dynflow is 10 seconds. This might cause a slight responsiveness drop for smaller jobs, but is probably way too frequent for jobs running on thousands of hosts. Maybe computing the value from the number of hosts (which we know before we start polling) would be the way to go.

Fixes #20466 - Use polling in RunHostsJob

---

app/models/concerns/foreman_remote_execution/taxonomy_extensions.rb

This reverts commit 82627b3c731aab3c79c4d95974325e2188903ac4.
Just to see what's actually broken with this.
We want to get a release that is compatible with 1.15 and 
it seems the original solution was not actually merged yet.

Fixes #21168 - Workaround for rails5 callbacks 

---

lib/foreman_remote_execution/engine.rb

The current setting of the `parameter_filter` was not allowing the
:execution parameter on the interface correctly.

Fixes #21178 - correct strong parameters on Nic::Interface

---

app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb
app/helpers/concerns/foreman_remote_execution/job_templates_extensions.rb
app/models/concerns/foreman_remote_execution/host_extensions.rb
app/models/concerns/foreman_remote_execution/smart_proxy_extensions.rb
lib/foreman_remote_execution/engine.rb

This is only intended for the 1.15 and 1.16, the nightlies should
keep the change and the proper fix should be done in Katello
to make it work again.

Fixes #21242 - revert using prepend instaed of alias_method_chain

---

app/models/concerns/foreman_remote_execution/taxonomy_extensions.rb

Rails 4 doesn't raise any issue when callback is not found and it
doesn't even know the raise option. Due to this, it considers the
additional option being a sign of need for re-definition of the
original callback, instead of just making it as skipped.
This patch sets the `raise => false` only for Rails 5, where it's
needed.

Refs #21168 - raise => false only for Rails 5

---

lib/foreman_remote_execution_core/script_runner.rb

- d770b64 fixes the missing constant
- 4dd59b9 makes the `#with_disconnect_handling` method rescue `IOError`, which is raised when the remote host reboots (or at least on ruby-2.4.1)

Fixes #21308, #21310 - Handle power actions on remote host better

---

app/controllers/job_invocations_controller.rb

Due to a change in Foreman core if we call triggering_params in REX, we receive
a Hash instead of ActiveController::Params. Merging a Hash into unpermitted
Params leads to the merged Hash not being #permitted? and causing
ActiveModel::ForbiddenAttributesError when trying to mass-assign the
triggering_params when creating a new job.
Related to theforeman/foreman commit 1ccf4df

Fixes #22168 - Fix ActiveModel::ForbiddenAttributesError

---

db/migrate/20180112125015_fix_taxable_taxonomies_job_template.rb

In #20708, we were converting the taxable_taxonomies association for
Templates. ProvisioningTemplate and PTable were converted, but not
JobTemplate. This commits completes the migration for remote execution.

Fixes #21888 - convert the taxable_taxonomies for JobTemplate

---

db/migrate/20150903192731_add_execution_to_interface.rb

This also has an added benefit of running much faster, especially for
installations that have a large number of interfaces.

Fixes #22421 - Correct Nic migration for Rails 5

---

app/helpers/job_invocation_output_helper.rb
app/views/template_invocations/_output_line_set.html.erb

There are client-side libraries that can do this, and I'd argue that's
the way it should be done. However, given the state of affairs with
gemified assets (we don't know if we're going to move to npm or
something like that) and the fact I already had this code ready, this
could be a temporary solution to display nicer console output.
Taken from https://github.com/theforeman/foreman_remote_execution/pull/134/files

Fixes #12105 - Parse ANSI terminal codes into colorful HTML

---

app/lib/actions/remote_execution/run_hosts_job.rb
app/models/job_invocation.rb
app/services/ui_notifications/remote_execution_jobs/base_job_finish.rb
db/seeds.d/50-notification_blueprints.rb
test/unit/actions/run_hosts_job_test.rb

see how it works
ready for later customization, job_invocation would return different notification builder class set per feature

Fixes #22237 - notification on success run

---

.hound.yml
app/controllers/api/v2/job_invocations_controller.rb
test/functional/api/v2/job_invocations_controller_test.rb

The API for JobInvocation could accept a 'feature' param which finds the
REX feature and creates the JobInvocation for said feature with all the
right parameters.
This saves other plugins from having to find the template ID associated
with the feature they want to run.
Here's a screencast showcasing this feature - clicking on "run playbook" sends a POST request with the feature & required inputs/host ids
https://gfycat.com/gifs/detail/SpottedOfficialCarpenterant

Fixes #22605 - JobInvocation API accepts 'feature' param

---

.rubocop.yml
app/models/job_invocation.rb
app/models/job_invocation_composer.rb
app/models/remote_execution_feature.rb
app/models/setting/remote_execution.rb
app/views/job_invocations/_form.html.erb
db/migrate/20180202072115_add_notification_builder_to_remote_execution_feature.rb
db/migrate/20180202123215_add_feature_id_to_job_invocation.rb
test/unit/job_invocation_composer_test.rb

This allows defining a custom notification builder for feature, if you want to see example usage, see https://github.com/theforeman/foreman_openscap/pull/326
the fact we now store the feature makes it easy in future to add more customization, e.g. job invocation page, based on it

Fixes #22609 - customizable notifications per feature

---

app/controllers/api/v2/job_invocations_controller.rb
app/models/job_invocation_composer.rb
test/functional/api/v2/job_invocations_controller_test.rb

The API currently only accepts a list of host IDs as parameters for the
JobInvocation CREATE method when using a feature.
It should also be able to accept a search query.

Fixes #22670 - Allow search query on JobInvocation API

---

app/controllers/job_invocations_controller.rb
app/models/job_invocation_composer.rb
test/functional/job_invocations_controller_test.rb

The UI should accept template inputs through the URL to display
the JobInvocation new form with pre-filled fields.
For example,
https://centos7-devel.lobatolan.home/job_invocations/new?feature=
ansible_run_insights_plan&inputs[plan_id]=3&inputs[organization_id]=20
would find the 'ansible_run_insights_plan' feature and 'plan_id' /
'organization_id' as pre-filled fields.
A small screencast demonstrating this feature around 1:10 -  https://webmshare.com/1WQee

Fixes #22604 - Accept input values as GET params in UI

---

db/migrate/20180226095631_change_task_id_to_uuid.rb
foreman_remote_execution.gemspec
test/unit/actions/run_hosts_job_test.rb
test/unit/concerns/foreman_tasks_cleaner_extensions_test.rb

Required after https://github.com/theforeman/foreman-tasks/pull/315 goes in

Fixes #22688 - Use UUID column type for storing task UUIDs

---

app/controllers/api/v2/job_invocations_controller.rb
app/models/job_invocation_composer.rb
config/routes.rb
lib/foreman_remote_execution/engine.rb
test/factories/foreman_remote_execution_factories.rb
test/functional/api/v2/job_invocations_controller_test.rb

Fixes #20692 - Add API for rerunning jobs

---

db/migrate/20160113162007_expand_all_template_invocations.rb

Steps to reproduce:
1. Have a postgres DB
2. enable `foreman-tasks` plugin, disable REX
3. `bundle exec rake db:create && bundle exec rake db:migrate`
4. Enable REX
5. Try to run `bundle exec rake db:migrate` again, without this fix it should fail with the error described in the issue
When we tried to do `.includes([:sub_tasks => :locks])` we tried to join `JobInvocation` with `ForemanTasks::Task` but the column used to match the records were of different types. If we don't do this join, we sacrifice a bit of performance by not loading all the needed data at once, but retrieving later should be done using `SELECT ... WHERE` which should work.

Fixes #22807 - Do not join on columns of possibly different types

---

test/functional/api/v2/job_templates_controller_test.rb

related to https://bugzilla.redhat.com/show_bug.cgi?id=1539042

added asserts to template details test

---

app/models/job_invocation_composer.rb

The problem here is that the hidden is under `job_invocation` key so feature was always ignored when user went through the form.

Fixes #22974 - store feature coming via form

---

app/models/remote_execution_provider.rb

f9d116105f70041f639f23675884d7e43ad9a1be started to depend on these methods being present in the base model. This ensures it doesn't crash when providers don't implement these methods.

Refs #21457 - Provide the expected interface in the base model

---

app/views/job_invocations/show.html.erb

In `app/views/job_invocations/show.html.erb`, we load the webpack
assets currently by calling a path:
*webpack_asset_paths('remoteexecution'
Since #23215 simplified the name of plugin bundles to just be the name
of the plugin (instead of "name of the plugin minus dashes and
spaces"), it should be changed to:
*webpack_asset_paths('foreman_remote_execution'

Fixes #23297 - Webpack assets path changed

---

app/models/job_invocation.rb
app/models/job_template.rb

while this is not entirely necessary, it would be good to be consistent with other models from plugins and core and have the audited definition first (it must preceed Taxonomix inclusion)

Fixes #22993 - refactor audits definitions

---

lib/foreman_remote_execution_core/script_runner.rb

In e65c15a, the `process` call was replaced with `loop` for no obvious
reason. This change leads potentially for the commands to get stuck.
I've reproduced this by trying `sudo` effective method without `sudo`
being present on the system.

Refs #21731 - revert using `loop` instead of `process`

---

app/models/concerns/foreman_remote_execution/host_extensions.rb
app/models/remote_execution_provider.rb
app/models/ssh_execution_provider.rb
test/unit/concerns/host_extensions_test.rb
test/unit/remote_execution_provider_test.rb

We change the way how we extend the host params to be compatible with
the `host_param` helper.
We also use the `host.host_param` if possible, as it has better
performance properties (the value gets memorized and it doesn't
recalculate the smart variables every time it's called.

Fixes #22483 - use host.host_param instead of host.params if possible

---

foreman_remote_execution_core.gemspec

This keeps in the SPDX compatible version

Remove duplicate license tag in core gemspec

---

app/controllers/api/v2/template_invocations_controller.rb
app/views/api/v2/template_invocations/base.json.rabl
app/views/api/v2/template_invocations/template_invocations.json.rabl
app/views/template_invocations/show.html.erb
config/routes.rb
lib/foreman_remote_execution/engine.rb
test/functional/api/v2/template_invocations_controller_test.rb

Fixes #23163 - Fix breadcrumbs in template invocation details

---

app/views/template_invocations/show.html.erb

Fixes #24085 - Include missing link in breadcrumbs

---

app/lib/actions/remote_execution/run_host_job.rb
lib/foreman_remote_execution_core/fake_script_runner.rb

This fixes the error with undefined method build, as well as issue with
checking the exit status, as in case of exception, it's actually
'EXCEPTION' string.

Fixes #24113 - fix fake executor

---

app/controllers/api/v2/job_templates_controller.rb
test/functional/api/v2/job_templates_controller_test.rb

There was a problem with the API structure, it didn't work since day one.
The `ssh` sub entry was not recognized by `strong params`, making the `ssh`
object (hash) and children not to be accessible.
This PR fixes the issue, but "breaks" the bad API documentation that existed
before.

Fixes #23394 - Unable to set effective user for job templates

---

app/controllers/job_templates_controller.rb
test/factories/foreman_remote_execution_factories.rb
test/functional/job_templates_controller_test.rb

This should fix
```
Warning! Template is missing Missing template job_templates/preview, templates/preview, application/preview with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rabl]}. Searched in: * "/home/inecas/Projects/ws/foreman-rex/foreman-rails5/app/views" * "/home/inecas/Projects/ws/foreman-rex/foreman_ansible/app/views" * "/home/inecas/Projects/ws/foreman-rex/foreman_remote_execution/app/views" * "/home/inecas/Projects/ws/foreman-rex/foreman-tasks/app/views" * "/home/inecas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/apipie-rails-0.5.9/app/views"
```
when …

fixes #24240 - replace render text with plain

---

app/helpers/remote_execution_helper.rb

When the user visits the job invocation details page, we rendered the
templates for first 20 hosts, which made the page load slowly. With
this change we first try to look into a task for this host, which may
contain the already rendered template.

Fixes #20776 - Do not re-render template if it can be loaded

---

app/models/job_template.rb
test/unit/job_template_test.rb

Originally we used job_category.

Fixes #14019 - Use template name as default description template

---

app/models/remote_execution_feature.rb

Using table_exists? in db:create doesn't work anymore.

Fixes #24698 - RemoteExecutionFeature.register Rails 5.2 fix

---

app/lib/actions/remote_execution/run_hosts_job.rb
app/models/input_template_renderer.rb
app/models/job_invocation.rb
test/unit/input_template_renderer_test.rb

This is a backport of https://github.com/theforeman/foreman_remote_execution/pull/374. Because 1.5-stable doesn't have the updated template renderer code, we can't just cherry-pick the 1.6 commit.

Fixes #24866 - Backport template renderer caching for 1.5-stable

---

app/controllers/api/v2/job_invocations_controller.rb
test/functional/api/v2/job_invocations_controller_test.rb

Before this commit we failed with 500: Internal Server Error

Fixes #24930 - Make output fail with 404 when job is missing

---

app/assets/stylesheets/foreman_remote_execution/template_invocation.css.scss
app/helpers/job_invocation_output_helper.rb
app/views/template_invocations/_output_line_set.html.erb

For some reason the output uses CRLF to mark a newline, writing CRs into
the terminal window led to line numbers not matching the lines. Also we
were splitting the output on newlines and trailing empty fields were
omitted.
To reproduce run the following
```shell
printf "\none\n"
printf "\ntwo\n"
printf "\nthree\n"
```

Fixes #22209 - Render empty lines properly in output

---

app/helpers/job_invocations_helper.rb
app/helpers/remote_execution_helper.rb
app/models/job_invocation.rb
test/factories/foreman_remote_execution_factories.rb
test/functional/api/v2/job_invocations_controller_test.rb
test/unit/job_invocation_test.rb

If a job is still running the behavior stays the same as it was. However if the
job is finished, rerunning the job will execute it also on hosts which were not
even planned and therefore don't have a template invocation.

Fixes #22750 - Rerun failed should rerun also on cancelled hosts

---

app/models/template_invocation_input_value.rb
test/unit/input_template_renderer_test.rb

Before this patch even if an input was not marked as required, the
validations wouldn't let the user execute a job where a value for this
job was not provided.

Fixes #22510 - Make inputs with options really optional

---

app/controllers/api/v2/remote_execution_features_controller.rb
app/controllers/cockpit_controller.rb
app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb
app/models/setting/remote_execution.rb
app/models/ssh_execution_provider.rb
config/routes.rb
lib/foreman_remote_execution/engine.rb
test/functional/cockpit_controller_test.rb

This adds a "Web Console" button next to the "Schedule Remote Job"
button in the title row of a host page.
The button links to a specially configured Cockpit instance.  It's
location is configured with the new remote_execution_cockpit_href
setting.
The Cockpit instance will use the new /cockpit_redirect path to get a
token via OAuth style redirection.

Fixes #25534 - Seamless cockpit integration

---

app/views/job_invocations/_form.html.erb

This pull request is a follow up on https://projects.theforeman.org/issues/27302 and https://community.theforeman.org/t/changing-the-default-from-static-to-dynamic-query-for-rex/14649
It will look like this with the change:

Fixes #27302 - Make query type option more visible

---

app/assets/stylesheets/foreman_remote_execution/job_invocations.css.scss
app/helpers/remote_execution_helper.rb

Links using method=post are rails hack, let's just use `button_to` and just style the form to behave.

Fixes #27883 - use button_to for post links

---

.rubocop.yml
lib/foreman_remote_execution_core/async_scripts/control.sh
lib/foreman_remote_execution_core/async_scripts/retrieve.sh
lib/foreman_remote_execution_core/polling_script_runner.rb
lib/foreman_remote_execution_core/script_runner.rb

Depends on:
This patch addes ability to take control over the job, allowing things
like surviving restarts and other advanced stuff. The main commands
allowing this is:
- `$CONTROL_SCRIPT manual-control` : turn on the manual control
- `echo hello | $CONTROL_SCRIPT update` : send output to the job
- `$CONTROL_SCRIPT finish $EXIT_CODE` : mark the job as finished
with corresponding $EXIT_CODE
Currently, this only works when proxy rex plugin is configured with
`:async: true`.
It also involves refoctoring to make majority of the control scripts
static files, and dynamically generate only `env.sh` script, containing
dynamic data only, that other scripts can source from.
A sample template I've been testing this with:
```ruby
if [ -z "$CONTROL_SCRIPT" ]; then
cat <<EOF
The script can be run only …
```

Fixes #26428 - exposed $CONTROL_SCRIPT and manual-mode

---

extra/cockpit/foreman-cockpit
extra/cockpit/foreman-cockpit.service

I have found out that `cockpit-ws` is actually the cockpit service, I thoguht it's some kind of helper script that does not have a policy. It has a policy and a domain and a port. Therefore wrapper is not only unnecessary but it causes it to start in an incorrect domain.
Thus we need to remove the wrapper, also we need a different port than 9090 (used by Katello) or 9999 (which is already in use in SELinux as `jboss_management_port_t`). So I suggest 19090 which is not used either by IANA or SELinux.
We need this patch to get into 1.24 in order to get SELinux working, sorry guys.

Refs #28072 - remove SELinux wrapper

---

webpack/react_app/components/jobInvocations/index.js

This reimplements functionality that was once provided by patternfly-react[1],
but was removed in commit 937d2d764a449e31276f1291fc528ff7ed625106. This commit
can be reverted when it gets re-added back there.
I tried opening https://github.com/patternfly/patternfly-react/pull/3299 against PF-react, we'll see how it goes there
[1] - https://github.com/patternfly/patternfly-react/

Fixes #28247 - Show chart overall result

---

app/views/job_invocations/_form.html.erb

The previous implementation of autocomplete relied on a legacy js which was
recently dropped from Foreman. This PR uses the new react component for
autocomplete. The drawback is the react component render the search box as an
input, not as a textarea. Sadly the underlying libraries don't seem to be
flexible enough to allow using a textarea easily.
Requires:

Fixes #28372 - Fix targeting autocompletion

---

extra/cockpit/foreman-cockpit-session

`foreman-cockpit-session` reads a configuration in YAML which uses symbols as
keys. Before this patch, doing so resulted in the 
```
Psych::DisallowedClass: Tried to load unspecified class: Symbol
```
being raised.

Fixes #28691 - Load symbols when parsing yaml

---

test/unit/input_template_renderer_test.rb

https://ci.theforeman.org/job/foreman_ansible-pull-request/244/database=postgresql,label=fast,ruby=2.5/#showFailuresLink

Fixes #28702 - Remove variable lookup keys from tests

---

app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb
lib/foreman_remote_execution/engine.rb

**Description**
Add _Jobs_ button to Details section on host edit page. Button goes to Job invocations page with filter set to `name=host.example.com`

Fixes #27324 - Add Jobs button to host detail page

---

app/controllers/concerns/foreman/controller/parameters/targeting.rb
app/helpers/job_invocations_helper.rb
app/models/job_invocation_composer.rb
app/models/targeting.rb
app/views/api/v2/job_invocations/main.json.rabl
app/views/job_invocations/_card_target_hosts.html.erb
app/views/job_invocations/_form.html.erb
db/migrate/20200204123702_targeting_add_taxonomies.rb

Add Location and Organization to Job invocations, so users will now see in which context job has been run.
**List of changes:**
* Current Organization & Location are displayed in `/job_invocations/new` form
* Organization & Location in which job has been run are now displayed in the Targeting section on Job invocation edit page.

Fixes #25144 - Include taxonomies in Job invocation targeting

---

app/controllers/job_invocations_controller.rb
app/helpers/job_invocations_helper.rb
app/views/job_invocations/_card_target_hosts.html.erb
app/views/job_invocations/_form.html.erb

Add Location and Organization to Job invocations, so users will now see in which context job has been run.
**List of changes:**
- Current Organization & Location are displayed in `/job_invocations/new` form
- Organization & Location in which job has been run are now displayed in the Targeting section on Job invocation edit page.

Fixes #25144 - Display taxonomies on Job invocation pages

---

app/models/job_invocation_composer.rb
test/unit/job_invocation_composer_test.rb

In some environments when you create a job invocation with end_time the end_time hash keys would be unsorted which caused the creation to fail.

Fixes #29048 - cant create job with end time

---

app/models/job_invocation.rb
test/unit/job_invocation_test.rb

puppet_options user input is optional input, and after moving the `Run Puppet once` button to REX. it runs `Puppet Run Once - SSH Default` task without `puppet_options` so it doesn't populated and therefore presented in the UI as `%{puppet_options}`

Fixes #28997 - remove %{puppet_options} from the format_description

---

app/controllers/job_invocations_controller.rb
app/views/job_invocations/_form.html.erb
app/views/job_invocations/_rerun_taxonomies.html.erb

When user is trying to re-run job in different Organization or Location, warning on re-run page is displayed.
**How to test:**
- Run job in Default organization & Default location
- Switch to different org/loc
- Rerun job
Warnings about taxonomies are displayed.

Fixes #25149 - Warning for Job taxonomies in re-rerun

---

app/views/job_invocations/show.html.erb

Job invocation page can be easily extended from other plugins, like this:
```
engine.rb
extend_page "job_invocations/show" do |cx|
cx.add_pagelet :main_tabs,
:partial => "job_invocations/leapp_report",
name: _('Leapp report'),
:id => 'leapp_report',
:onlyif => Proc.new { |subject| subject.job_category == 'Leapp' }
end
```

Fixes #29361 Add pagelet to Job invocation detail

---

app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb

Extract loading links for multi-button from method to separate method, so other plugins can extend it and add its own links, like this:
```
def rex_host_features(*args)
super + [link_to(_('Preupgrade check with Leapp'), new_job_invocation_path(:host_ids => [args.first.id], :feature => 'leapp_preupgrade')),
link_to(_('Upgrade with Leapp'), new_job_invocation_path(:host_ids => [args.first.id], :feature => 'leapp_upgrade'))]
end
```

Fixes #29399 - Make schedule_job_multi_button method extendable

---

app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb

after feedback from the whole team, we decided for us that cockpit in a new tab is way more convenient.

Fixes #29422 - web console should open in a new tab or window

---

config/routes.rb
test/functional/job_invocations_controller_test.rb

For building Remediation plan with thousands of IDs `GET` method can be problem.

Add POST route for JobInvocations#new

---

app/helpers/job_invocations_helper.rb
app/views/job_invocations/_card_user_input.html.erb
app/views/job_invocations/_user_input.html.erb

The original intention in #29465 was that it would use the hidden_value method
if available and continue working as it used to if not. Because of this,
dependency on Foreman wasn't bumped, because it was supposed to work even with
older releases than 2.1 which provided hidden_value. However, we missed some
places and because of that, release 3.2.0 wasn't compatible with Foreman 2.0.

Fixes #29793 - Do not rely on hidden_value being defined

---

.eslintrc
.gitignore
.travis.yml
package.json
scripts/travis_run_js_tests.sh

* For TravisCI `node.js` version have been updated to 10 & 12
*  Added / updated packages:
```
"@theforeman/builder": "^4.2.1",
"@theforeman/eslint-plugin-foreman": "4.2.1",
"@theforeman/stories": "^4.2.1",
"@theforeman/test": "^4.2.1",
"@theforeman/vendor-dev": "^4.2.1",
```
* Removed some obsolete packages (now part of `@theforeman/*`)
* `npm run lint` is now following styling code for foreman core and plugins.
* Functions like `testComponentSnapshotsWithFixtures` from `@theforeman/test` can be used now.
* Added `stories` scripts

Fixes #29878 - Move to foreman-js provided tooling

---

app/models/concerns/foreman_remote_execution/orchestration/ssh.rb

We should probably not rollback whole deletion transaction. Since the entry is missing, there is nothing we can do about it.

Fixes #29843 - SSH known_deletion failure is non-fatal

---

app/lib/actions/remote_execution/run_host_job.rb
app/models/remote_execution_provider.rb
app/services/default_proxy_proxy_selector.rb
app/services/internal_proxy_proxy_selector.rb

A Satellite 6.8 feature requires a support from remote execution to be able to run a job from the proxy co-located on the same machine as foreman/satellite. The feature is downstream only, so we can rely on Katello being there and we can use Katello's code to determine which proxy is the right one. However this creates this weird situation where we have a downstream only feature and rex depends on katello. I'd rather avoid less reliable methods of determining the proxy like hostname comparison.
I suggest we get this in as-is now and shortly after 2.1 is out we introduce a new feature to the smart proxy, which will mark the proxy as being co-located on the same machine as foreman/satellite and once it gets in, we change the marked code here to use that marker instead of whatever katello …

Fixes #29783 - Allow overriding proxy selector in jobs

---

app/models/concerns/foreman_remote_execution/orchestration/ssh.rb
test/models/orchestration/ssh_test.rb

That means:
- skip the removal if ip and/or hostname if nil
- skip the removal if the host/interface is a new record
- add more tests

Fixes #29962 - Make known hosts key removal less error prone

---

app/controllers/api/v2/job_invocations_controller.rb
app/controllers/api/v2/template_invocations_controller.rb
app/helpers/job_invocations_helper.rb
app/views/api/v2/job_invocations/main.json.rabl
test/functional/api/v2/job_invocations_controller_test.rb

Fixed API endpoints:
* `show` - Now `@hosts` are filtered based on user's permissions.
* `output` - Now looking for host in Job Invocation scope plus checking if user is authorized to see host's results.
* `raw_output` - same as for `output`

RM#29972 - API::JobInvocations - Host permissions

---

app/assets/stylesheets/foreman_remote_execution/job_invocations.scss
app/views/job_invocations/_card_target_hosts.html.erb

in job invocations long host list breaks page, the page is too long to really use or understand when there are too many hosts in the list.
`infoblock` class was removed a long time ago.
before:
After

Fixes #30213 - long host list breaks page

---

app/assets/stylesheets/foreman_remote_execution/job_invocations.scss
app/views/job_invocations/index.html.erb

Fixes #30330 - Added word-wrap for description field

---

lib/foreman_remote_execution_core.rb
lib/foreman_remote_execution_core/log_filter.rb

When debug ssh logging is enabled, it passes a facility as an argument
and a block to the logger. Our implementation of log filter, which
allows only messages of required severity (or higher) to be logger
discarded the block. For this reason, log messages showed only
facility, which wasn't really useful in any way.

Fixes #30225 - Make ssh debug logging show useful data

---

.github/workflows/ci.yml
app/controllers/job_invocations_controller.rb
app/views/job_invocations/_tab_hosts.html.erb
app/views/job_invocations/show.html.erb
app/views/job_invocations/show.json.erb
lib/foreman_remote_execution/engine.rb
webpack/__mocks__/foremanReact/components/Pagination/PaginationWrapper.js
webpack/__mocks__/foremanReact/components/SearchBar.js
webpack/__mocks__/foremanReact/constants.js
webpack/__mocks__/foremanReact/redux/API/APISelectors.js
webpack/__mocks__/foremanReact/redux/middlewares/IntervalMiddleware/IntervalSelectors.js
webpack/react_app/components/TargetingHosts/TargetingHosts.js
webpack/react_app/components/TargetingHosts/TargetingHostsActions.js
webpack/react_app/components/TargetingHosts/TargetingHostsHelpers.js
webpack/react_app/components/TargetingHosts/TargetingHostsPage.js
webpack/react_app/components/TargetingHosts/TargetingHostsPage.scss
webpack/react_app/components/TargetingHosts/TargetingHostsSelectors.js
webpack/react_app/components/TargetingHosts/__tests__/TargetingHostsPage.test.js
webpack/react_app/components/TargetingHosts/__tests__/TargetingHostsSelectors.test.js
webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHosts.test.js.snap
webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHostsPage.test.js.snap
webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHostsSelectors.test.js.snap
webpack/react_app/components/TargetingHosts/__tests__/fixtures.js
webpack/react_app/components/TargetingHosts/index.js

Requires https://github.com/theforeman/foreman/pull/7771
* Searching and pagination is now done in React way --> No page reloads
* Fixed issue with Loading spinner: when no items were found, loading spinner was displayed instead of message `No hosts found`
* `job_invocations_controller.rb#show` refactored, resources for Targeting hosts table are loaded only when they are needed.

Fixes #30206 - Targeting hosts - Search & pagination as React components

---

app/models/concerns/foreman_remote_execution/orchestration/ssh.rb

We hook onto Host::Managed and Nic::Managed destroy to perform the ssh known
host key removal. However, we use the host as a base from which we figure out
from which proxies the keys should be removed. Because discovered hosts have
managed nics, but do not implement #remote_execution_proxies, the error
undefined method `remote_execution_proxies` was raised when deleting discovered
hosts.

Fixes #30399 - Fix error when deleting discovered hosts

---

app/views/api/v2/job_invocations/main.json.rabl
test/functional/api/v2/job_invocations_controller_test.rb

(cherry picked from commit 428e04423e3fdcbfc023d702b2c5dd7c4c5cb5dd)

Fixes #30628 - show empty hosts in job invocation api cp 3.3

---

app/models/concerns/api/v2/interfaces_controller_extensions.rb
app/views/api/v2/interfaces/execution_flag.json.rabl
lib/foreman_remote_execution/engine.rb

adds 'execution' attribute to https://foreman/api/hosts/host_id/interfaces

Fixes #20689 - make REX interface accessible by API

---

lib/foreman_remote_execution/engine.rb

Due to how Rails load code, it could happen that the module with extensions
would get prepended too late and it would be ignored. By prepending the
extensions from an initializer we make it happen earlier in the boot process.

Fixes #30685 - Ensure run button appears in job templates page

---

app/models/concerns/foreman_remote_execution/host_extensions.rb

It would also be possible to add the IPv6-subnet as `:subnet6`, but this would require adding `:subnet6` to the [`strategy`-list in Foreman-Tasks](https://github.com/theforeman/foreman-tasks/blob/904c07ca7f2be446e5453eeb271f9c4bc98628de/app/services/foreman_tasks/proxy_selector.rb#L11).
I would like to put this up for discussion :-)

Fixes #30808 - Use IPv6-proxy if no IPv4-proxy

---

app/controllers/job_templates_controller.rb

The toast notification component supports in `warning`, `success`, `info` and `error` type
I used the `success` type here though it can also be `info`

Fixes #30947 - replace the notice flash type

---

app/views/template_invocations/_output_line_set.html.erb

`Time.at` is being passed in a string value which results in a "can’t convert String into an exact number" error message whenever you attempt to view the results of a job run on a host.
Another user reported the same issue: https://community.theforeman.org/t/job-invocations-cant-convert-string-into-an-exact-number/18921

Resolve issue when viewing successful job invocation

---

app/lib/actions/remote_execution/run_hosts_job.rb
test/unit/actions/run_hosts_job_test.rb

By accounting for missing hosts in a job we broke running jobs on hosts past
first batch. There is a module which periodically polls states of sub-tasks and
overwrites then numbers we were using to decide whether to spawn next batch or
not.
With this change we store the expected total count under a different key in
task's output so it won't get overwritten by the included polling module. For
compatibility with already existing jobs we use the value under the original key
in task's output in case the task doesn't have the value set under the new key.

Fixes #30859 - Prevent job from getting stuck after first batch

---

app/views/api/v2/job_invocations/main.json.rabl

Each template invocation was in this structure with no way of knowing which host it belongs to:
```
{
"template_id": 175,
"template_name": "Package Action - Ansible Default",
"template_invocation_input_values": [
{
"template_input_name": "state",
"template_input_id": 76,
"value": "present"
},
},
```
after this pr:
```
{
"template_id": 175,
"template_name": "Package Action - Ansible Default",
"host_id": 94,
"template_invocation_input_values": [
{
"template_input_name": "state",
"template_input_id": 76,
"value": "present"
},
},
```
Blocking https://github.com/theforeman/hammer_cli_foreman_remote_execution/pull/36

Refs #30816 - Show host id for template input

---

app/controllers/foreman_remote_execution/concerns/api/v2/registration_controller_extensions.rb
app/models/concerns/foreman_remote_execution/host_extensions.rb
app/views/api/v2/registration/_form.html.erb
lib/foreman_remote_execution/engine.rb
test/functional/api/v2/registration_controller_test.rb

Extending Registration module with option to specify which Host's interface is going to be set as primary for REX.
Follow up to https://github.com/theforeman/foreman/pull/8121, which is also requirement for this PR.
**Features**
* Add `:remote_execution_interface` to allowed arguments & variables
* Extend UI Form with field for `:remote_execution_interface` (_All Hosts > Register Host_)
* Set Host REX interface during host registration
**How to test**
* Register host to the Foreman
```
curl -X GET "https://foreman.example.com/register?location_id=2&organization_id=1" --user admin:changeme | bash
```
* Add multiple interfaces (`dummy1`, `dummy2`, `dummy3`)
* In UI generate command again, but this time with specified `remote_execution_interface`
* Run registration again & check that …

Fixes #31237 - Extend Registration module with :remote_execution_inteface

---

webpack/react_app/components/TargetingHosts/TargetingHostsPage.js
webpack/react_app/components/TargetingHosts/TargetingHostsPage.scss
webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHostsPage.test.js.snap

6px margin for pagination was removed from the table in: https://github.com/theforeman/foreman/pull/8133

Fixes #31297 - Table pagination in react has extra space

---

app/models/foreign_input_set.rb

Export of the foreign input set sets the wrong template name. Therefore
reimporting it fails, because it creates a circular dependency. To
reproduce, just export a template with at least one foreign input set
defined and try to import it back (with overwrite enabled).
This patch correctly looks at the target template instead of exported
template itself.

Fixes #26671 - fix exporting foreign input set

---

app/models/host_status/execution_status.rb

This PR introduces a clickable execution status at host detail page that leads to last job invocation of given host

fixes #31428 - making execution status clickable

---

app/views/template_invocations/show.html.erb

When changing the taxonomy contex on the template invocation page,
the host that was displayed may no longer be viewable in the new
context. Instead of erroring out show an informational message.

Fixes #31562 - Don't crash when switching context on invocation

---

.prettierrc
config/routes.rb
lib/foreman_remote_execution/engine.rb
webpack/JobWizard/JobWizard.js
webpack/JobWizard/index.js
webpack/Routes/routes.js
webpack/__mocks__/foremanReact/history.js
webpack/global_index.js

A starting page for the PF4 job creation wizard will be in the lab features menu.
It doesn't have any content, yet

Fixes #31116 - add exprimental page for job wizard

---

app/controllers/api/v2/job_invocations_controller.rb
app/models/job_invocation.rb
test/functional/api/v2/job_invocations_controller_test.rb

Fixes #31933 - Mark output as complete if task is missing

---

lib/foreman_remote_execution_core.rb

There is no guarantee that it was loaded by something else at the point where we try to use it. It is safer to try loading it.

Fixes #32209 - Try to require task launcher registry in advance

---

package.json
webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/__tests__/JobWizard.test.js
webpack/JobWizard/__tests__/__snapshots__/JobWizard.test.js.snap
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.test.js
webpack/JobWizard/steps/CategoryAndTemplate/__snapshots__/CategoryAndTemplate.test.js.snap
webpack/JobWizard/steps/CategoryAndTemplate/index.js
webpack/JobWizard/steps/form/GroupedSelectField.js
webpack/JobWizard/steps/form/SelectField.js
webpack/JobWizard/steps/form/__tests__/GroupedSelectField.test.js
webpack/JobWizard/steps/form/__tests__/SelectField.test.js
webpack/JobWizard/steps/form/__tests__/__snapshots__/GroupedSelectField.test.js.snap
webpack/JobWizard/steps/form/__tests__/__snapshots__/SelectField.test.js.snap
webpack/__mocks__/foremanReact/common/helpers.js
webpack/__mocks__/foremanReact/redux/API/index.js
webpack/__mocks__/foremanReact/routes/common/PageLayout/PageLayout.js

Depends on https://github.com/theforeman/foreman_remote_execution/pull/546
There is a typeahead issue in PF4 that is fixed in 2020.14, so user can't search for a template in the select

Fixes #31342 - add Category and template step to job wizard

---

lib/foreman_remote_execution/engine.rb
package.json
webpack/global_index.js
webpack/index.js
webpack/react_app/components/RecentJobsCard/RecentJobsCard.js
webpack/react_app/components/RecentJobsCard/constants.js
webpack/react_app/components/RecentJobsCard/index.js
webpack/react_app/components/RecentJobsCard/styles.css
webpack/react_app/extend/fills.js
webpack/react_app/extend/reducers.js

This adds a card to the experimental host details page

Fixes #31267 - Add recent jobs card to host details page

---

app/controllers/api/v2/job_invocations_controller.rb
app/lib/foreman_remote_execution/provider_input.rb
app/models/invocation_provider_input_value.rb
app/models/job_invocation_composer.rb
app/models/remote_execution_provider.rb
app/models/template_invocation.rb
app/models/template_invocation_provider_input_value.rb
app/views/job_invocations/_form.html.erb
db/migrate/20210312074713_add_provider_inputs.rb
test/unit/job_invocation_composer_test.rb

Adds inputs that will be displayed for each template
of a specified provider.

Fixes #32081 - Add provider specific inputs

---

app/controllers/api/v2/job_invocations_controller.rb
app/models/job_invocation_composer.rb
test/functional/api/v2/job_invocations_controller_test.rb
test/unit/job_invocation_composer_test.rb

I'll need someone to verify the correctness of the change I made here. The tests I removed assert that the job invocations API should take `host_ids` as an input but that param  is undocumented. I think those tests were meant to describe the behavior of `JobInvocationComposer.for_feature` so I updated the tests accordingly, while also updating the controller to correctly pass the `search_query` param into `for_feature`

Fixes #32107 - job invocation create API should work with the feature param

---

webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.test.js
webpack/JobWizard/steps/CategoryAndTemplate/__snapshots__/CategoryAndTemplate.test.js.snap
webpack/JobWizard/steps/CategoryAndTemplate/index.js
webpack/JobWizard/steps/form/GroupedSelectField.js
webpack/JobWizard/steps/form/SelectField.js
webpack/__mocks__/foremanReact/redux/API/APISelectors.js

When one of the api calls in job wizard fails there is now an error shown.
Currently there are only api calls to get  the categories list and templates list

Fixes #32439 - Add error state to job wizard

---

app/models/host_status/execution_status.rb
app/models/job_invocation.rb

Allows searching recurring job invocations by template name
and target host.
`recurring = true && targeted_host_id = 3 && pattern_template_name = "Ansible Roles - Ansible Default" && status = queued`

Fixes #32628 - Add search definitions for jobs

---

app/models/job_invocation_composer.rb
app/models/targeting.rb
test/unit/job_invocation_composer_test.rb

When a job is rerun through the UI, we take out selected fields from the
old job, render the form and then submit it. Essentially it behaves like
running a new job with some fields pre-populated.
When rerunning a job through the api, there is no form middle step. We
just take the old job, run it through job composer, get a new job out of
it and then link the new job's targeting against old job's hosts. This
step was triggering validations on the hosts.

Fixes #32742 - Ensure job rerun through api works with invalid hosts

---

app/models/job_invocation.rb

Monitor > Jobs page can not be rendered because total_hosts_count
fails. Unfortunately the total_hosts_count method tries to execute
total_count in ApplicableErrataInstall but this should normally done in
REX > RunHostsJob.
This happens for Jobs created with older REX plugins (< 2.3 of foreman).

Fixes #32797 - Fix issue that monitor > jobs page could not render

---

app/controllers/job_invocations_controller.rb
app/models/host_status/execution_status.rb
app/models/job_invocation.rb
app/views/job_invocations/index.html.erb
test/unit/job_invocation_test.rb

This fixes an issue of AmbigousColumn result in JobInvocation query.
It addresses two issues that lead to the error together.
1. We've joined tasks table in two ways, which was not necessary and
caused double join on foreman_tasks table.
2. We've not referenced table name in the result mapper, which caused
Ambigous column even when the tasks table was properly aliased.
Also fixing N+1 query introduced by 8f0ba81e3634c2f015814ee77e1b303f77ef3faa. That should probably be a separate PR, but it would have conflicts with this one, so I thought we can do it at once, the resulting history should be fine.

Fixes #32793 - unambigous result field on index query

---

app/controllers/ui_job_wizard_controller.rb
lib/foreman_remote_execution/engine.rb
webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/__tests__/integration.test.js
webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
webpack/JobWizard/steps/AdvancedFields/Fields.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/AdvancedFields/__tests__/__snapshots__/AdvancedFields.test.js.snap
webpack/JobWizard/steps/form/FormHelpers.js
webpack/JobWizard/steps/form/Formatter.js
webpack/JobWizard/steps/form/NumberInput.js
webpack/JobWizard/steps/form/__tests__/Formatter.test.js
webpack/JobWizard/steps/form/__tests__/__snapshots__/Formatter.test.js.snap
webpack/__mocks__/foremanReact/components/SearchBar.js

Depends on https://github.com/theforeman/foreman_remote_execution/pull/553
render the inputs from `template_inputs_with_foreign` into the advanced field step
New:
old:

Fixes #31459 - Add advanced template input to job wizard

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/steps/Schedule/QueryType.js
webpack/JobWizard/steps/Schedule/RepeatOn.js
webpack/JobWizard/steps/Schedule/ScheduleType.js
webpack/JobWizard/steps/Schedule/StartEndDates.js
webpack/JobWizard/steps/Schedule/__tests__/StartEndDates.test.js
webpack/JobWizard/steps/Schedule/index.js
webpack/JobWizard/steps/form/SelectField.js

Only add components without the functionality and without the advanced options.
The Repeat field will be added more in depth in a different pr
~~Depends on: https://github.com/theforeman/foreman_remote_execution/pull/551~~

Fixes #31500 - Add basic schedule to job wizard

---

app/helpers/remote_execution_helper.rb

When login as non-admin user with viewer permission, the host
list in the job invocation page is taking long time to load.
This is fixed by passing the cached collection when checking
the user permission so the application doesn't need to repeat
the same query for every row.

Fixes #32986 - Slow loading of hosts in job invocation page

---

app/views/templates/ssh/module_action.erb
app/views/templates/ssh/puppet_run_once.erb

The code we had was most likely supposed to link the feature against an
already existing template. In case the template didn't exist when the
seeds were run, nothing established the relationship.

Fixes #29950 - Map Run Puppet Once template to its feature

---

foreman_remote_execution_core.gemspec

Note, keys have to be in PEM format, otherwise opening a connection will
fail with the following trace.
```
2021-07-19T13:14:19  [E] Error initializing command - RuntimeError No digester supplied:
net-ssh-4.2.0/lib/net/ssh/transport/key_expander.rb:15:in `expand_key'
net-ssh-4.2.0/lib/net/ssh/transport/cipher_factory.rb:67:in `get'
net-ssh-4.2.0/lib/net/ssh/authentication/ed25519.rb:111:in `initialize'
net-ssh-4.2.0/lib/net/ssh/authentication/ed25519.rb:152:in `new'
net-ssh-4.2.0/lib/net/ssh/authentication/ed25519.rb:152:in `read'
net-ssh-4.2.0/lib/net/ssh/key_factory.rb:113:in `block in classify_key'
net-ssh-4.2.0/lib/net/ssh/key_factory.rb:60:in `load_data_private_key'
net-ssh-4.2.0/lib/net/ssh/key_factory.rb:43:in `load_private_key' …
```

Refs #27770 - Add support for ed25519 keys with net-ssh ~> 4.2.0 

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
webpack/JobWizard/steps/AdvancedFields/DescriptionField.js
webpack/JobWizard/steps/AdvancedFields/__tests__/DescriptionField.test.js

Adds the final field to the advanced step. Depends on https://github.com/theforeman/foreman_remote_execution/pull/554
As the step to edit the template inputs doesn't exist yet, it doesn't use the value of the input but the name of the input instead.
New:
onclick it moves to this:
old:
Original generate description is here:
https://github.com/theforeman/foreman_remote_execution/blob/ab166f9d760d0148bdd5dd0672503f57acdf47bb/app/assets/javascripts/foreman_remote_execution/template_invocation.js#L102-L122

Fixes #31460 - add description field to job wizard

---

lib/foreman_remote_execution_core/script_runner.rb

Catch exception when user generates ssh key with ed25519 algorithm and task will fail with proper error message.

Fixes #27769 - Catch exception when using ed25519 algorithm

---

app/views/templates/ssh/power_action.erb

Prevents errors like shutdown: command not found

Fixes #32496 - Append usual paths to the end of PATH for power action

---

app/helpers/remote_execution_helper.rb

Cancelling and aborting a job from the template invocation details does
a POST to foreman_tasks. Before this change, it followed the link and
displayed a JSON response provided by the controller. After this change
the request is done in background without leaving the current page.

Fixes #32675 - Perform host cancel without following the link

---

app/models/job_invocation_composer.rb

We claimed to have support for iso8601 timestamps, but in reality we
discarded timezone information and assumed the timestamp to be in UTC.

Fixes #31705 - Handle timezones when scheduling jobs through API

---

app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb

Users who can't run the Host REX jobs should not see the REX buttons.

Fixes #33143 - hide rex buttons for unpriviledged

---

foreman_remote_execution_core.gemspec
lib/foreman_remote_execution_core/script_runner.rb

Backport of https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/62

Fixes #33002 - Do not use deprecated net-ssh options

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/__tests__/integration.test.js
webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.test.js
webpack/JobWizard/steps/HostsAndInputs/SelectedChips.js
webpack/JobWizard/steps/HostsAndInputs/TemplateInputs.js
webpack/JobWizard/steps/HostsAndInputs/__tests__/SelectedChips.test.js
webpack/JobWizard/steps/HostsAndInputs/__tests__/TemplateInputs.test.js
webpack/JobWizard/steps/HostsAndInputs/index.js
webpack/JobWizard/steps/Schedule/index.js
webpack/JobWizard/steps/form/Formatter.js
webpack/JobWizard/steps/form/WizardTitle.js

To only include the hosts selection method (without the actual selection), show host chips and show inputs.
Depends on: https://github.com/theforeman/foreman_remote_execution/pull/554 for the input templates

Fixes #31492 - Add basic hosts and inputs page

---

app/lib/actions/remote_execution/run_hosts_job.rb
test/unit/actions/run_hosts_job_test.rb

The middleware always ran after every plan batch, effectivelly limiting
the tasks sent to proxy to a currectly planned batch.
This moves to a Trigger by action and evoking that action when needed
and than last time at the end.
The trigger action is defined in theforeman/foreman-tasks#640 so that will need to go first and then we need bump dependency.

Fixes #32854 - allow proxy_batch_size to work properly

---

.rubocop_todo.yml
app/lib/actions/remote_execution/run_hosts_job.rb
app/mailers/rex_job_mailer.rb
app/models/rex_mail_notification.rb
app/services/ui_notifications/remote_execution_jobs/base_job_finish.rb
app/views/rex_job_mailer/job_finished.html.erb
app/views/rex_job_mailer/job_finished.text.erb
db/seeds.d/50-notification_blueprints.rb
db/seeds.d/95-mail_notifications.rb
test/unit/actions/run_hosts_job_test.rb

User can subscribe to either all job notifications, successful jobs or
failed jobs or no notifications. The user who runs the job would then be
notified based on the subscription. It supports both plain text and html
emails.
Since now we have a way to run the notification even on failure, the
notification drawer notification has been also added in case the job
fails.

Fixes #31564 - add email notification

---

webpack/react_app/components/RecentJobsCard/RecentJobsCard.js

In a medium-size resolution, the recent audit card becomes too small for rendering all tabs without scrolling:
before:
after:

Refs #33311 - fix recent audit card alignment

---

app/lib/actions/remote_execution/run_hosts_job.rb
app/models/remote_execution_provider.rb
test/unit/actions/run_hosts_job_test.rb

Allow number of HostTasks to be send to proxy in one batch to be tweaked
per every provider. If provider won't supply value, we still default to
`Setting['foreman_tasks_proxy_batch_size']`

Fixes #32032 - proxy batch sizing per provider

---

app/views/job_invocations/refresh.js.erb

When a user clicks the refresh button, the browser does a request in background
and replaces the entire form with the response it receives. However, the tooltip
is rendered directly in body and therefore was left around when the form was
replaced. This change simply removes all currently displayed tooltips once the
refresh is performed.

Fixes #32677 - Remove refresh tooltip after form refresh

---

app/controllers/api/v2/job_invocations_controller.rb
test/functional/api/v2/job_invocations_controller_test.rb

When organization_id or location_id parameters were supplied, the nested
resource handling machinery resolved the organization (or location) to
be the parent resource instead of the expected job invocation.

Fixes #33007 - Handle taxonomies gracefully on output endpoints

---

webpack/JobWizard/JobWizard.scss

Fixes #33513 - Job wizard transperent menu in small screens

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/__tests__/integration.test.js
webpack/JobWizard/__tests__/validation.test.js
webpack/JobWizard/autofill.js
webpack/JobWizard/index.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/HostsAndInputs/SelectedChips.js
webpack/JobWizard/steps/HostsAndInputs/__tests__/HostsAndInputs.test.js
webpack/JobWizard/steps/HostsAndInputs/__tests__/TemplateInputs.test.js
webpack/__mocks__/foremanReact/routes/RouterSelector.js

url example to get fill: 
`/experimental/job_wizard?host_ids%5B%5D=100&host_ids%5B%5D=67`
`/experimental/job_wizard?search=os+%3D+CentOS`
depends on: https://github.com/theforeman/foreman_remote_execution/pull/578

Fixes #33094 - auto fill job wizard with hosts

---

package.json
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/form/Formatter.js
webpack/JobWizard/steps/form/SelectField.js

When there is a select template input the ui is showing the first result as selected but it's value is not selected in the templateValues state

Fixes #33368 - job wizard fake auto select template values

---

package.json
webpack/JobWizard/steps/Schedule/RepeatCron.js
webpack/JobWizard/steps/Schedule/RepeatDaily.js
webpack/JobWizard/steps/Schedule/RepeatHour.js
webpack/JobWizard/steps/Schedule/RepeatMonth.js
webpack/JobWizard/steps/Schedule/RepeatOn.js
webpack/JobWizard/steps/Schedule/RepeatWeek.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js
webpack/JobWizard/steps/Schedule/index.js

Updates foreman-js to use `toggleAriaLabel`. another pr that updates it to the same version is https://github.com/theforeman/foreman_remote_execution/pull/663

Fixes #33822 - job wizard add validation for repeat types

---

package.json
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
webpack/JobWizard/steps/HostsAndInputs/index.js
webpack/JobWizard/steps/Schedule/RepeatOn.js
webpack/JobWizard/steps/form/Formatter.js
webpack/JobWizard/steps/form/SelectField.js

if the template input is not required there should be an empty option
depends on https://github.com/theforeman/foreman_remote_execution/pull/663

Fixes #33662 - Job wizard allow unselecting template inputs

---

app/views/job_templates/_custom_tabs.html.erb

This method will go away from foreman core, we need to replace it.
The https://github.com/theforeman/foreman/pull/8951 removes this deprecated method.

Fixes #34001 - remove usage of deprecated auto_complete_search

---

app/lib/actions/remote_execution/run_host_job.rb
app/views/template_invocations/show.html.erb

Adds a link to used foreman proxy to template invocation detail page
Also links the per-host task against the proxy, making the proxy appear in Locks tab in task's details

Fixes #34032 - Make proxy used for REX more easily discoverable

---

lib/foreman_remote_execution/engine.rb
test/unit/job_invocation_report_template_test.rb

We've changed the name of the default template in core, so we also need to change the default.

Fixes #34132 - change default template to the new template name

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/autofill.js
webpack/JobWizard/index.js
webpack/JobWizard/steps/CategoryAndTemplate/index.js
webpack/JobWizard/steps/HostsAndInputs/__tests__/HostsAndInputs.test.js

depends on: https://github.com/theforeman/foreman_remote_execution/pull/626
example url: `?feature=ansible_run_playbook&inputs[playbook]=hello`
There are some changes in the use effect of selecting category and template.
workflow should be:
No feature in url? select first category -> get categories templates -> select first template
feature in url? select the template -> select the templates category -> get categories templates -> use effect sees that there is a feature in the url and doesnt select the first template. Also deletes the feature so if a user selects a different category the first template of the category will be selected.

 Fixes #33125 - autofill wizard with feature and inputs

---

app/controllers/ui_job_wizard_controller.rb
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/__tests__/integration.test.js
webpack/JobWizard/steps/CategoryAndTemplate/index.js

The default template is set in the Remote Execution settings
depends on: https://github.com/theforeman/foreman_remote_execution/pull/629

Fixes #32990 - job wizard select default template

---

webpack/JobWizard/JobWizard.scss
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/steps/HostsAndInputs/HostSearch.js
webpack/JobWizard/steps/form/Formatter.js
webpack/__mocks__/foremanReact/constants.js

Now when a user has a search input field in the template they can use it's bookmarks.
(Before the foreman fix the new bookmark modal will choose only the last text entered as the value so we can only had one bookmark button perpage)

Fixes #33737 - Add bookmarks to templates in job wizard

---

app/views/templates/README.md

This removes the outdated README.md file which was referencing the community templates repo.

Fixes #34269 - remove outdated README

---

app/mailers/rex_job_mailer.rb

We were using private Rails method `ActionMailer::Base#add_template_helper` that was never ment to be used.
This method is dropped by Rails 6.1 in https://github.com/rails/rails/commit/cb3b37b37975ceb1d38bec9f02305ff5c14ba8e9 and we need to stop using it.
This simply replaces it by supported `helper` is enough.

Fixes #34297 - replace dropped Rails method

---

app/models/concerns/foreman_remote_execution/nic_extensions.rb
test/unit/concerns/host_extensions_test.rb

Previously we required each host to have exactly one execution interface. There
was a mechanism in place which would ensure host had at least one execution
interface by marking the primary interface as execution if the host had none.
However this wasn't 100% reliable.
This loosens the requirement from exactly one to 0 or 1 and removes the
mechanism enforcing host has at least 1 execution interface.
This is arguably more correct alternative to https://github.com/theforeman/hammer_cli_foreman_remote_execution/pull/43

Fixes #34452 - Allow hosts to have no execution interface

---

app/views/templates/ssh/package_action.erb

At the moment, when you want to install a non-existing package on a client with zypper, the installation of the package fails. However, in the return code evaluation of the installation, the return code is overwritten with `0` if the installation failed. This causes the whole job to be shown as successful even if it was not.
This PR removes the line of code where the return code is set to `0`, which causes the return code to be evaluated correctly in line 115/116.

Prevent ssh action for zypper to return 0 on failure

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
webpack/JobWizard/steps/form/GroupedSelectField.js

when loading template list template selection is disabled and the selected template is shown as empty.
after selecting a template, until the template is loading all the steps are disabled

Fixes #33388 - disable template related fields when loading

---

webpack/JobWizard/steps/form/GroupedSelectField.js

Adding the same fields as in `SelectField`
https://github.com/theforeman/foreman_remote_execution/blob/7c73948716a099abefc2248fed3c3a10ed073bdd/webpack/JobWizard/steps/form/SelectField.js#L46-L47

Fixes #34657 - Add aria label to job wizard template select

---

app/helpers/remote_execution_helper.rb
app/lib/actions/remote_execution/run_host_job.rb
app/models/remote_execution_provider.rb
app/models/ssh_execution_provider.rb
app/views/templates/script/check_update.erb
app/views/templates/script/module_action.erb
app/views/templates/script/package_action.erb
app/views/templates/script/power_action.erb
app/views/templates/script/puppet_agent_disable.erb
app/views/templates/script/puppet_agent_enable.erb
app/views/templates/script/puppet_install_modules_from_forge.erb
app/views/templates/script/puppet_install_modules_from_git.erb
app/views/templates/script/puppet_run_once.erb
app/views/templates/script/run_command.erb
app/views/templates/script/service_action.erb
db/migrate/20220321101835_rename_ssh_provider_to_script.rb
lib/foreman_remote_execution/engine.rb
test/unit/remote_execution_provider_test.rb

Currently the new provider is just an alias to the SSH provider to make
the transition easier and not require making this change across all
dependenat plugins at once.

Fixes #34653 - Rename SSH provider to script

---

webpack/react_app/components/FeaturesDropdown/index.js

The `scedule a job` button redirects to the new job page, but it isn't linked to the current host.

Refs #34260 - fix the 'schedule a job' button in new host

---

app/models/concerns/foreman_remote_execution/host_extensions.rb
app/views/api/v2/host/main.rabl
lib/foreman_remote_execution/engine.rb
webpack/global_index.js
webpack/react_app/components/HostKebab/KebabItems.js
webpack/react_app/extend/fillKebabItems.js

This adds the missing `web console` button from the legacy host page.

Fixes #34600 - add web/cockpit console to host's kebab

---

webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/ReviewDetails/index.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js
webpack/react_app/components/RecentJobsCard/RecentJobsCard.js

Corrects Overview tab - Host detail page - incorrect use of sentence case
Job card - actions in the kebab should be;
“View all jobs”
“View finished jobs”
“View running jobs”
“View scheduled jobs”
and a couple more I found.

Fixes #34799 - New host detail page sentence case fixes

---

webpack/react_app/components/HostKebab/KebabItems.js

I could probably use `<Link>` from PF4, but just to be consistent with the core I've used this way.

Fixes #34835 - Open Cockpit console in a new tab

---

app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb

Companion to https://github.com/Katello/katello/pull/10096

Fixes #32104 - Retain tasks used for errata reporting for longer time

---

webpack/JobWizard/steps/form/SearchSelect.js

It shouldn't, so a user can select many items

Fixes #33844 - wizard multiple select closes after select

---

webpack/react_app/components/TargetingHosts/TargetingHostsConsts.js
webpack/react_app/components/TargetingHosts/TargetingHostsPage.js
webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHostsPage.test.js.snap
webpack/react_app/components/TargetingHosts/__tests__/fixtures.js
webpack/react_app/components/TargetingHosts/index.js

Uses the same hack to fill the search input text as the job wizard using `getResults`

Fixes #34471 - Add bookmarks to jobs targeting host

---

webpack/react_app/components/FeaturesDropdown/index.js

Concern was brought up at host details meeting that users are confused by having multiple primary buttons on screen (e.g. errata Apply & 'Schedule a job')
It's technically possible but difficult to make 'Schedule a job' button secondary only if there is another primary button on screen.
For simplicity it was decided instead to just make 'Schedule a job' secondary all the time.

Fixes #34900 - Make 'Schedule a job' button secondary

---

app/models/job_invocation_composer.rb
test/functional/api/v2/job_invocations_controller_test.rb

A minimal solution leveraging the existing errors flattener.

Fixes #33397 - Propagate validation errors from triggering

---

webpack/JobWizard/steps/Schedule/RepeatWeek.js
webpack/JobWizard/submit.js

When selecting weekly recurrence in the job wizard and running the job, this error will show: 
`"cronline":["00 13 * * [object Object] is not valid format of cron line"]`
fixes also an issue where Monday was treated as 0 day when it should be sunday.

Fixes #35077 - Cant run job wizard with weekly

---

webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/form/DateTimePicker.js
webpack/JobWizard/steps/form/Formatter.js

When a template has a date field instead of using a text box, the job wizard should use a datetime picker.
To test might need to reinstall npm packages as the `includeSeconds` option is newish

Fixes #35154 - Job wizard user input for date use datepicker

---

app/controllers/ui_job_wizard_controller.rb
config/routes.rb
lib/foreman_remote_execution/engine.rb
webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/JobWizardPageRerun.js
webpack/JobWizard/__tests__/JobWizardPageRerun.test.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/autofill.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/CategoryAndTemplate/index.js
webpack/Routes/routes.js
webpack/__mocks__/foremanReact/common/hooks/API/APIHooks.js

changed the menu url to `experimental/job_wizard/new`
to use this pr go to `experimental/job_wizard/_ID_/rerun` as its experimental.
UI changes are adding the org/location alerts.
Patternfly guidelines say `If an alert message applies globally to the content on a page, place the alert in the page header area just below the title.`

Fixes #35084 - Add rerun to job wizard

---

app/models/host_status/execution_status.rb

when calculating details of execution status.

Fixes #35307 - Do not rely on tasks always being there

---

app/models/remote_execution_provider.rb
lib/foreman_remote_execution/engine.rb
test/unit/remote_execution_provider_test.rb

When assigning REX proxies to a subnet, proxy features are matched
exactly against registered REX provider names. Since there is a one
letter mismatch, proxies having only Script feature would not show as
available in the list.

Fixes #35308 - Make script provider name match proxy feature

---

app/models/job_invocation.rb
app/models/remote_execution_provider.rb
app/views/overrides/subnets/_rex_tab_pane.html.erb
lib/foreman_remote_execution/engine.rb
test/unit/remote_execution_provider_test.rb

Without this, running a job would fail with
`NoMethodError: undefined method 'host_id=' for ["SSH", "Script"]:Array`

Refs #35308 - Propagate the new registered name to more places

---

webpack/react_app/extend/Fills.js

Changes from PR#725 accidentaly removes interface
field from registration form.
[0] https://github.com/theforeman/foreman_remote_execution/pull/725

refs #34970 - Host Registration - put interface back

---

webpack/react_app/extend/Fills.js

undoing - https://github.com/theforeman/foreman_remote_execution/pull/754
the `name` key was not used and `id` was used instead, `id` was always undefined.

Fixes #35471 - Slot & Fill renders only one component

---

app/models/remote_execution_provider.rb
test/unit/remote_execution_provider_test.rb

::RemoteExecutionProvider does a lookup inside class instance variables set on it. When a custom provider subclasses ::RemoteExecutionProvider, this lookup is done inside the subclass, where the variables are not set so this lookup returns nil.
The other piece is `Host::Managed#remote_execution_proxies(provider)` returning all the proxies, if `provider` is `nil`.
The unfortunate outcome of those two above is that when using subclassed providers (such as in Ansible), proxies were not filtered based on available features.
The fix causes the lookup to be performed on the top-level class, instead of in the subclass.

Fixes #35515 - Fix proxy selection for subclassed providers

---

app/lib/actions/remote_execution/run_hosts_job.rb

Rails cache store does not support regex, but does support glob patterns.

Fixes #31310 - Use redis glob pattern during job finalization

---

webpack/react_app/components/FeaturesDropdown/actions.js

in the new host details page, in the "schedule a job" drop down.
currently the `runFeature` function assumes that by calling post `/job_invocations?feature=${feature}&host_ids%5B%5D=${hostId}` the job would be executed, but sometimes the call will be redirected to the job form
the options for the `responseURL` are
* `.../job_invocations/78`
* `.../job_invocations?feature=leapp_upgrade&host_ids%5B%5D=139`
Left the success toast as there is no way for the ui knowing if it will be redirected or not before receiving a response

Fixes #35644 - Allow host details features open job form

---

lib/foreman_remote_execution/engine.rb
lib/foreman_remote_execution/tasks/explain_proxy_selection.rake

```shell
==> Strategy subnet
no proxies available using this strategy
==> Strategy fallback
no proxies available using this strategy
==> Strategy global
1) proxy1.example.com - 0 tasks
2) foreman.example.com - 1 tasks
==> Strategy registered_through
no proxies available using this strategy
As of now, SSH job would use proxy proxy1.example.com, determined by strategy global.
```

EXPLAIN ANALYZE for proxy selection

---

app/controllers/job_invocations_controller.rb
app/controllers/ui_job_wizard_controller.rb
app/helpers/job_invocations_helper.rb
app/helpers/remote_execution_helper.rb
app/views/job_invocations/new.html.erb
config/routes.rb
lib/foreman_remote_execution/engine.rb
webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/JobWizardPageRerun.js
webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/autofill.js
webpack/JobWizard/index.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.test.js
webpack/JobWizard/steps/CategoryAndTemplate/index.js
webpack/JobWizard/submit.js
webpack/Routes/routes.js

* move job wizard from `/experimental/job_wizard/new` to `job_invocations/new`
* move job form from `job_invocations/new` to `old/job_invocations/new`
* remove job wizard from the lab menu tab
* fix bug where hosts list in the url can be a single host (and not an array)
* fix bug where users get to the wizard from the host details page, and then go back (to host details) and again to the job wizard caused some data to be not displayed correctly in the wizard because the `component state` was deleted but the `redux store` stayed the same
* remove unused `job_invocations_buttons` 
* fixed wizards breadcrumbs to go to the correct all jobs url
* if users want to use the old form/new wizard there is a link to the other type in the form/wizard

Fixes #35584 - Make job wizard the default way to create jobs

---

app/controllers/ui_job_wizard_controller.rb
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/steps/AdvancedFields/__tests__/__snapshots__/AdvancedFields.test.js.snap
webpack/JobWizard/steps/HostsAndInputs/index.js
webpack/JobWizard/steps/form/Formatter.js
webpack/JobWizard/steps/form/ResourceSelect.js
webpack/JobWizard/steps/form/SearchSelect.js

Fixed:
* Review step crashing when there is input in a resource input
* rerun not filling resource inputs
* submit sending wrong data for resource inputs
The `ResourceSelect` "new" component is an edited version of `SearchSelect` which was used for it in the previous pr.

Fixes #35725 - job wizard resource inputs not working

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/JobWizard.scss
webpack/JobWizard/JobWizardHelpers.js
webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
webpack/JobWizard/steps/AdvancedFields/DescriptionField.js
webpack/JobWizard/steps/AdvancedFields/Fields.js
webpack/JobWizard/steps/HostsAndInputs/__tests__/TemplateInputs.test.js
webpack/JobWizard/steps/form/FormHelpers.js
webpack/JobWizard/steps/form/Formatter.js
webpack/JobWizard/steps/form/SelectField.js

Adds a button next to every field that can have a default value to reset the field to that value.
Will show button only for fields that have a default value
example screenshot:

Fixes #35721 - reset to default button to job wizard fields

---

app/lib/actions/remote_execution/proxy_action.rb
app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/template_invocation_progress_logging.rb
app/models/template_invocation.rb
app/models/template_invocation_event.rb
db/migrate/20220713095705_create_template_invocation_events.rb
foreman_remote_execution.gemspec

Before this change all job outputs were stored deep in actions' outputs.
When we wanted to retrieve them, we had load an instance of the action
and then let it assemble all the outputs into a form that the rest of
the application could consume.
This is a first step away from it. Outputs now live in a separate table,
which gets populated as things happen.
TODO:
In the future this should allow us to:
- have a more precise progress reporting (in spirit of https://github.com/theforeman/foreman_remote_execution/pull/712) by inserting "control" events into the log
- retrieve only new outputs from the smart proxy instead of retrieving all of them every single time
- load the outputs in chunks when showing them in the ui
Requires:
- https://github.com/theforeman/foreman-tasks/pull/689

Fixes #35218 - Store job outputs outside of tasks

---

webpack/react_app/components/FeaturesDropdown/actions.js

Fix for https://github.com/theforeman/foreman_remote_execution/pull/762 after https://github.com/theforeman/foreman_remote_execution/pull/758 broke it and changed the url from `/job_invocations?feature=` to `/job_invocations/new?feature=`

Refs #35584 - fix url for host details feature open job form

---

lib/foreman_remote_execution/engine.rb

Correcting a spelling mistake for effective user in the remote execution settings form

Fixes #35804 - spelling correction for effective user

---

app/lib/actions/remote_execution/proxy_action.rb
app/lib/actions/remote_execution/run_host_job.rb
db/migrate/20221129170145_redefine_template_invocation_events_index.rb

The new storage for job outputs assumed that for each combination of template_invocation_id, event_type, timestamp, there would be up to 1 entry. Considering timestamps are stored with microsecond precision, and sp-rex-ssh collects outputs once per second, this felt somewhat reasonable. However, during transfer the timestamps get serialized (and then deserialized), reducing the precision to seconds in the process. REX then complained about duplicate records when trying to upsert the incoming outputs into the db.
This change introduces sequence_ids to template_invocation_events table. These ids represent the ordering of an output event within the line of events for a given template invocation and as such, every combination of (template_invocation_id, sequence_id) must be unique.
Eventually …

Fixes #35806 - Introduce sequence_id to new outputs

---

app/models/job_invocation.rb
app/models/template_invocation.rb
test/unit/job_invocation_test.rb
webpack/react_app/components/TargetingHosts/TargetingHostsLabelsRow.js
webpack/react_app/components/TargetingHosts/TargetingHostsLabelsRow.scss
webpack/react_app/components/TargetingHosts/TargetingHostsPage.js
webpack/react_app/components/TargetingHosts/TargetingHostsSelectors.js
webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHostsPage.test.js.snap
webpack/react_app/components/TargetingHosts/index.js
webpack/react_app/components/jobInvocations/AggregateStatus/index.js
webpack/react_app/components/jobInvocations/AggregateStatus/index.test.js
webpack/react_app/components/jobInvocations/index.js
webpack/react_app/redux/actions/jobInvocations/index.js
webpack/react_app/redux/reducers/jobInvocations/index.js

Known issues:
- the row with chips is most likely wrongly aligned
- the donut chart itself does not indicate the selection, haven't found an easy way how to do that
- the search doesn't really work for hosts which don't have their task yet, but that is nothing new
https://user-images.githubusercontent.com/7326770/171000566-46ac5faf-eef7-49d1-befa-72bd20e0eb98.mp4

Fixes #24962 - Make graph in job details clickable

---

db/migrate/20210816100932_rex_setting_category_to_dsl.rb

See:
https://github.com/theforeman/foreman/pull/9524
https://github.com/theforeman/foreman/pull/9524#issuecomment-1404661119

Fixes #36003 - Migration error 'column settings.category does not exist'

---

app/views/job_invocations/show.html.erb

We used charts.js from Foreman, but that was dropped in Foreman 3.0 (https://github.com/theforeman/foreman/commit/69379b51a33344de93836950565ecbfae0c4df23) and results in 404 errors when trying to load the job invocation page.

Fixes #36108 - do not load non-existant charts.js

---

app/controllers/job_invocations_controller.rb
config/routes.rb
lib/foreman_remote_execution/engine.rb

Draft until search is fixed in forms, as until then users cant really submit jobs from the legacy form

Fixes #35910 - Submit in legacy job form redirects wrong

---

webpack/JobWizard/autofill.js
webpack/JobWizard/steps/HostsAndInputs/__tests__/HostsAndInputs.test.js

The inputs get filtered later into advanced/template input, can be checked with `/job_invocations/new?feature=leapp_remediation_plan&inputs%5Bremediation_ids%5D="1%2C2%2C3"&inputs[run_preupgrade]=false`

Fixes #36127 - Cant pre-fill job wizard advanced inputs

---

app/controllers/ui_job_wizard_controller.rb
webpack/JobWizard/JobWizard.js
webpack/JobWizard/submit.js

Adding them in the api response as part of the advanced inputs so that the ui will treat them as template inputs, and split them on submit from the advanced inputs.
Tested that they were actually added with ` TemplateInvocation.last.provider_input_values.first.value`

Fixes #36096 - Add provider inputs to job wizard

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/__tests__/__snapshots__/integration.test.js.snap
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/__tests__/integration.test.js
webpack/JobWizard/__tests__/validation.test.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/AdvancedFields/__tests__/__snapshots__/AdvancedFields.test.js.snap
webpack/JobWizard/steps/HostsAndInputs/__tests__/HostsAndInputs.test.js
webpack/JobWizard/steps/HostsAndInputs/buildHostQuery.js
webpack/JobWizard/steps/HostsAndInputs/index.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js
webpack/JobWizard/submit.js

~~using the magic of `1=0` like ruby does at    `if displayed_search_query.blank?  Host.where('1 = 0')`~~
Checking if any of the host selections are selected after a user clicks the host input, if not it will show an error

Fixes #36089 - Job wizard default to no hosts selected

---

app/helpers/remote_execution_helper.rb

To prevent re-rendering of templates before showing them in the UI, we tried to pull them from the associated tasks. However, we only checked task's presence, not its state. This opened door to us trying to access data that is not there yet. The data should be there once the task goes gets planned completely.

Fixes #36114 - Prevent accessing dynflow internals until ready

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/StartsBeforeErrorAlert.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js
webpack/JobWizard/submit.js

Users could select a value in the schedule step, go to the review step, wait until the "startsbefore" time is in the past and submit the form.
this solves 2 issues:
1. check every 5 secs that "startsbefore" is still in the future, and disable the submit button if its not, and adds this alert no matter what step the user is in.
3. typo in the error toast that prevented users seeing an error if they submitted something invalid to the server 
had to switch the fake timer running in tests because of the added `setInterval` but test times don't look effected in my env.

Fixes #35975 - validate starts before value constantly in the job wizard

---

app/controllers/job_invocations_controller.rb
config/routes.rb
lib/foreman_remote_execution/engine.rb
webpack/react_app/components/RecentJobsCard/RecentJobsCard.js
webpack/react_app/components/RecentJobsCard/RecentJobsTable.js
webpack/react_app/components/RecentJobsCard/constants.js

* also changed the links in the dropdown to filter the hosts with `target_host_id` and not `host` for more correct results

Fixes #35147 - Hosts jobs card to show host job status

---

app/lib/actions/remote_execution/run_host_job.rb

With the template invocation events based implementation, checking exit status raised an exception if the task was still running (and the event was missing).

Fixes #36231 - Do not raise when checking exit status

---

webpack/JobWizard/JobWizard.scss

Fixing this:
Removed css was not needed as it was trying to solve the issue where users will expend the navigation (on small screen) and could not use the navigation, when the navigation is expanded it has `pf-m-expanded`

Fixes #36241 - job wizard - datepicker z index fix

---

webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/steps/ReviewDetails/ReviewDetails.test.js
webpack/JobWizard/steps/ReviewDetails/index.js

In the job wizard review step, users would like to click on the field title to jump to the step that edits it.
so clicking on `job temple` will jump to the template selection step, `Recurrence` will jump to one of the schedule steps...

Fixes #36275 - job wizard Jump to step from review

---

webpack/JobWizard/autofill.js

Fixes the bug:
User selects all hosts (not only all in page) in hosts page, and clicks on schedule a job
expected: search to be `name != ''` like in the old form

Fixes #36374 - Wizard should accept search='' in url

---

.eslintrc
.github/workflows/js_ci.yml
package.json

We keep forgetting adding ouia-ids to react component, this is a rule to alert us in the pr that we forgot.

Fixes #36564 - Add eslint rule to alert missing ouia-ids

---

app/controllers/ui_job_wizard_controller.rb

This previously defaulted to a combination of action_permission and controller name.

Fixes #36565 - Use correct permissions for job category lookup

---

app/views/job_templates/_custom_tabs.html.erb

Users cant edit and save Job templates without re-setting the job category. Job category should be filled in on edit

Fixes #36605 - Job category is not set in job template edit

---

app/models/job_template.rb
test/unit/job_template_test.rb

The `JobTemplate#import_custom_data` method removes metadata from a job template's contents. But the regex actually causes any ERB comment to be removed, not just the metadata at the top of the file:
This commit updates the regex so that only the first ERB comment is matched:

Fixes #36600 - Regex should only match the first ERB comment, not all

---

extra/cockpit/foreman-cockpit-session

Previously, we were parsing *all* messages that were being proxies so that we could inject effective user password in case it was needed. If network delays were introduce into the flow, messages could be framed in a way that we would not be able to parse them. Trying to parse an incomplete message could lead to an unhandle exception, which would terminate the session.
This patch keeps track of whether we still need to inject the autohrization message into the communication. From what I've seen, the authorization message is the second message being sent so we can stop inspecting messages quite early and thus significantly reduce the window in which the bug can be triggered.
This also does not look into the messages (apart from the first one) at all, if the remote user is already root or if …

Fixes #36619 - Reduce issues with cockpit message framing

---

webpack/JobWizard/JobWizard.js

Previously we kept the pre-filled values from the previous template and then sent them to the backend together with the inputs for the new template. This prevented the job from being started as the backend didn't know what to do with the extra inputs.

Fixes #36627 - Discard irrelevant inputs on template change

---

app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
foreman_remote_execution.gemspec
test/unit/actions/run_hosts_job_test.rb

This should resolve the issues with limit-based concurrency control. It now behaves slightly differently - per-host tasks don't get created at all until there is capacity for them.
Requires:
- https://github.com/Dynflow/dynflow/pull/428
- https://github.com/theforeman/foreman-tasks/pull/722
TODO:

Fixes #36707 - Adjust to v2 sub plans

---

app/controllers/api/v2/remote_execution_features_controller.rb
app/views/api/v2/remote_execution_features/available_remote_execution_features.json.rabl
config/routes.rb
lib/foreman_remote_execution/engine.rb
webpack/react_app/components/FeaturesDropdown/constant.js
webpack/react_app/components/FeaturesDropdown/index.js

Took the permissions from the old host page, schedule job button: https://github.com/theforeman/foreman_remote_execution/blob/0b75d16284b5abc8d121d4b3cf665d0122540f84/app/helpers/hosts_extensions_helper.rb#L56

Fixes #36751 - check permissions for schedule job button

---

db/migrate/20210517132916_add_host_proxy_invocations.rb

The migration file `2021051713291621250977 AddHostProxyInvocations` always gets treated as the latest migration when you try to do `rails db:rollback`. This is not ideal.
I think it's because the file is oddly named; it has 8 more characters in the timestamp than every other migration file. This causes Rails to think it's a newer timestamp, because I guess the number is the biggest or something?
Anyway, I tested it and it seems like renaming it to be in line with the other files works fine.

Fixes #36851 - Rename migration file so it doesn't break migrations

---

webpack/JobWizard/steps/HostsAndInputs/hostgroups.gql

`name` is the short name, while `title` is the full name, including the host group parent

Fixes #36881 - Display full hostgroup name in Job Wizard

---

app/lib/actions/remote_execution/event_helpers.rb
app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/run_hosts_job.rb
foreman_remote_execution.gemspec
lib/foreman_remote_execution/engine.rb
test/unit/actions/run_hosts_job_test.rb

Per host in job now have per feature events when the action succeeds or fails.
Per job now have general running/stopped/failed as well as per feature running/stopped/failed events. Note, both the generic and per-feature are emitted.

Fixes #36166 - Revamp job hooks

---

app/helpers/remote_execution_helper.rb
app/views/api/v2/job_invocations/base.json.rabl
config/routes.rb
lib/foreman_remote_execution/engine.rb
webpack/JobInvocationDetail/JobInvocationActions.js
webpack/JobInvocationDetail/JobInvocationConstants.js
webpack/JobInvocationDetail/JobInvocationOverview.js
webpack/JobInvocationDetail/JobInvocationSelectors.js
webpack/JobInvocationDetail/index.js
webpack/Routes/routes.js

The commit creates a new job invocation detail page ([see discussion](https://community.theforeman.org/t/rfc-job-invocation-detail-page-redesign/33839)) which is experimental until finished - you can find it in Lab Features or see `/experimental/job_invocations_detail/${JOB_ID}`. It includes the main information.
_Update:_ There is a link on the old detail page to the new one if the experimental labs setting is on.

Fixes #36823 - Create job invocations detail page with main info

---

app/views/templates/script/convert2rhel_analyze.erb

Workaround for the issue with 'convert2rhel analyze', where after the job run, OS is unassigned from the host.
See https://issues.redhat.com/browse/RHELC-1280

Fixes #36967 - convert2rhel analyze removes OS from the host

---

app/helpers/remote_execution_helper.rb
lib/foreman_remote_execution/engine.rb

In a separate PR I want to try to deal with the issue that react#index paths dont get the correct auths, but I think we should first return the job buttons to Rex Users. 
Added also `view_remote_execution_features` permission because I think normal users should be able to view the features? just not edit them
test: have a user with only rex user role, open `/job_invocations` before: no button, now: yes button.
Also for job reruns inside `job_invocations/id`, and  in host details page (some hosts are `infrastructure_host` and will need extra permission to run job).

Fixes #36974 - show run job button to rex users

---

app/controllers/ui_job_wizard_controller.rb
lib/foreman_remote_execution/engine.rb
webpack/JobWizard/JobWizardConstants.js
webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/PermissionDenied.js
webpack/JobWizard/index.js
webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
webpack/JobWizard/steps/HostsAndInputs/index.js

Depends on https://github.com/theforeman/foreman/pull/9902
It is showing missing permissions needed on the `/job_invocations/new` page. The "Proceed Anyway" button lets you look at the wizard even though it won't be working properly.
On the "Category and template" step it shows a warning alert if view_job_templates permission is missing:
On the "Target hosts and inputs" step it shows a warning alert if view_hosts permission is missing:

Fixes #36785 - Show permission error page for job wizard

---

.packit.yaml

the old url will go away at some point as we're dropping koji and while we could use the relevant copr for this, it felt more natural to use released bits

use yum.tfm.o for foreman bits

---

app/views/job_invocations/welcome.html.erb

related to https://github.com/theforeman/theforeman.org/pull/2089

Fixes #37041 - Change link to docs.theforeman.org

---

app/models/job_invocation.rb

```
Validation failed: Concurrency level: must be greater than 0
70

Fixes #37042 - Validate concurrency level is positive

---

app/helpers/remote_execution_helper.rb

of template invocations when the backing task is not yet created.

Fixes #37082 - Show 'Awaiting start' as status

---

test/functional/api/v2/job_invocations_controller_test.rb
test/functional/api/v2/template_invocations_controller_test.rb
test/helpers/remote_execution_helper_test.rb
test/unit/actions/run_host_job_test.rb
test/unit/actions/run_hosts_job_test.rb
test/unit/concerns/foreman_tasks_cleaner_extensions_test.rb
test/unit/concerns/host_extensions_test.rb
test/unit/concerns/nic_extensions_test.rb
test/unit/execution_task_status_mapper_test.rb
test/unit/input_template_renderer_test.rb
test/unit/job_invocation_composer_test.rb
test/unit/job_invocation_test.rb
test/unit/job_template_effective_user_test.rb
test/unit/job_template_test.rb
test/unit/remote_execution_feature_test.rb
test/unit/remote_execution_provider_test.rb
test/unit/renderer_scope_input_test.rb
test/unit/targeting_test.rb

Like
```
Use _(obj).must_equal instead. This will fail in Minitest 6.
```

Fix minitest warnings

---

package.json

Reverts theforeman/foreman_remote_execution#833
We do not need to pin to a Node 12 compatible version, and I need a change to test Webpack 5 ;-)

Revert "Pin @adobe/css-tools to ~4.2.0"

---

app/helpers/job_invocations_helper.rb
app/helpers/remote_execution_helper.rb
app/lib/actions/remote_execution/run_host_job.rb
app/views/job_invocations/_preview_hosts_list.html.erb
app/views/template_invocations/show.html.erb
webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/autofill.js
webpack/JobWizard/steps/HostsAndInputs/HostPreviewModal.js
webpack/JobWizard/steps/HostsAndInputs/SelectGQL.js
webpack/JobWizard/steps/HostsAndInputs/SelectedChips.js
webpack/JobWizard/steps/HostsAndInputs/hosts.gql
webpack/JobWizard/steps/HostsAndInputs/index.js
webpack/JobWizard/steps/ReviewDetails/index.js
webpack/JobWizard/steps/form/SearchSelect.js
webpack/JobWizard/steps/form/__tests__/SelectSearch.test.js

If the `display_fqdn_for_hosts` setting is set to false, show the short hostname on REX job pages.
Requires:
* https://github.com/theforeman/foreman/pull/9968

Fixes #36982 - display short hostname on REX job pages

---

app/models/host_status/execution_status.rb

Go to /hosts on the UI with about 72 hosts.
```
OLD:
2260 (SQL Queries)
2279
NEW:
2002
1992
```
SQL query:
```
SELECT "foreman_tasks_tasks".* FROM "foreman_tasks_tasks" INNER JOIN "foreman_tasks_links" ON "foreman_tasks_links"."task_id" = "foreman_tasks_tasks"."id" WHERE "foreman_tasks_tasks"."type" = $1 AND "foreman_tasks_tasks"."label" = $2 AND "foreman_tasks_links"."resource_id" = $3 AND "foreman_tasks_links"."resource_type" = $4  [["type", "ForemanTasks::Task::DynflowTask"], ["label", "Actions::RemoteExecution::RunHostJob"], ["resource_id", 46], ["resource_type", "Host::Managed"]]
```
This SQL Query was removed.  Old: 358 queries. New: 0
Reduced allocations: ~ 152106

Fixes #36944 - reduce the amount of SQL queries during grabbing host status

---

app/views/job_invocations/show.html.erb
app/views/job_invocations/show.js.erb
app/views/template_invocations/_refresh.js.erb

* to ensure correct loading order we need to wrap js scripts into content for
* '`webpack_asset_paths` is deprecated, use `content_for(:javascripts) { webpacked_plugins_js_for(plugin_name) }` instead.')
* `webpacked_plugins_css_for` is deprecated, plugin css is already loaded

Fixes #37185 - webpack 5 adjustments

---

app/lib/actions/remote_execution/proxy_action.rb
app/lib/actions/remote_execution/run_host_job.rb

The result of calling continuous_output was not persisted, so the original code didn't make much sense. `ContinuousOutput#sort!` returns the same thing as `ContinuousOutput#raw_outputs` so we can skip the second line completely.
`upsert_all` was updating the already existing values, so `exit_status` got updated multiple times with different timestamps. `insert_all` should just skip over the already existing values.

Fixes #37242 - Fix live output appearing multiple times

---

app/lib/actions/remote_execution/run_host_job.rb

The current one was placed in because of changes that happened back in 2016, it is not needed anymore.

Fixes #37323 - Rely on default implementation of delegated_output

---

app/views/templates/script/convert2rhel_analyze.erb

Remove the telemetry opt out since it's not being used by Convert2RHEL anymore.
https://issues.redhat.com/browse/SAT-24015

[SAT-24015] Remove telemetry option from conversion templates

---

webpack/JobWizard/JobWizardPageRerun.js

Both of the following should use the same phrasing:
webpack/JobWizard/JobWizardPageRerun.js
webpack/JobWizard/index.js
Right now the user experience is as follows:
When Creating a new Job through Monitor → Jobs → Run Job, while in the creation wizard, there is an option to “Use Legacy Form”
After Submitting the Job I land on the Job Result Page and click on Rerun which sends me back to the Job wizard, and now the option that was “Use Legacy Form” says " Use old Form"

Use consistent phrasing

---

app/controllers/api/v2/job_invocations_controller.rb
app/models/job_invocation.rb
app/models/job_invocation_composer.rb
app/views/api/v2/job_invocations/base.json.rabl
package.json
webpack/JobInvocationDetail/JobInvocationActions.js
webpack/JobInvocationDetail/JobInvocationConstants.js
webpack/JobInvocationDetail/JobInvocationDetail.scss
webpack/JobInvocationDetail/JobInvocationSelectors.js
webpack/JobInvocationDetail/JobInvocationSystemStatusChart.js
webpack/JobInvocationDetail/JobInvocationToolbarButtons.js
webpack/JobInvocationDetail/__tests__/MainInformation.test.js
webpack/JobInvocationDetail/__tests__/fixtures.js
webpack/JobInvocationDetail/index.js
webpack/JobWizard/JobWizardPageRerun.js
webpack/__mocks__/foremanReact/components/BreadcrumbBar/index.js
webpack/__mocks__/foremanReact/components/Head/index.js
webpack/__mocks__/foremanReact/components/HostDetails/DetailsCard/DefaultLoaderEmptyState.js
webpack/__mocks__/foremanReact/components/ToastsList/index.js
webpack/__mocks__/foremanReact/redux/API/APIActions.js
webpack/__mocks__/foremanReact/redux/API/APIConstants.js
webpack/__mocks__/foremanReact/redux/API/index.js
webpack/__mocks__/foremanReact/redux/middlewares/IntervalMiddleware/index.js

Adds global actions to the new job invocation detail page header:

Fixes #37286 - Add global actions to job invocation detail page

---

app/lib/actions/remote_execution/run_hosts_job.rb

Previously we sent the last batch event followed by a regular TriggerNextBatch event with correct number of batches. The proxy batch triggering action received the TriggerLastBatch event, set an internal flag, triggered a single batch and exited, the other event got discarded. This commit changes the ordering so that the TriggerNextBatch event is sent out first when planning is done.

Fixes #37590 - Trigger ready batches on planning finished

---

webpack/JobWizard/steps/HostsAndInputs/__tests__/HostsAndInputs.test.js

once every 2-4 test runs the test will fail with:
Warning: An update to %s inside a test was not wrapped in act(...).
Error: Uncaught [Error: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method
in Select (created by SearchSelect)
in SearchSelect (created by SelectGQL)
in SelectGQL (created by HostsAndInputs)
a useEffect cleanup function
in SearchSelect (created by SelectGQL)
in SelectGQL (created by HostsAndInputs)
in div (created by InputGroup)
SearchSelect
in SearchSelect (created by SelectGQL)
in SelectGQL (created by HostsAndInputs)
in div (created by InputGroup)
in InputGroup (created by HostsAndInputs)

Fixes #37635 - HostsAndInputs.test.js missing an await

---

app/lib/actions/remote_execution/run_host_job.rb
app/models/concerns/foreman_remote_execution/smart_proxy_extensions.rb
app/models/template_invocation.rb
app/views/template_invocations/show.html.erb
db/migrate/20240522093412_add_smart_proxy_id_to_template_invocation.rb
db/migrate/20240522093413_migrate_smart_proxy_ids_to_template_invocations.rb

Up until now we only stored it somewhere in the depths of tasks and it served us reasonably well, because we only showed the in template invocation's details.

Fixes #37493 - Store smart proxy id in template invocations

---

app/views/template_invocations/show.html.erb

Description of problem:  
After executing an "Ansible command" job the details page shows two links "scroll bottom" and "scroll top" but none of them works.
How reproducible:
Always
Steps to Reproduce:
1. Execute a "Remote Ansible Command" job
2. Enter into the Job details page
3. Click "Scroll to bottom" Link
Actual behavior:
Nothing happens
Expected behavior:
The page scrolls down.

Fixes #37594 - "Scroll to bottom/top" javascript links on job details page

---

app/views/templates/script/run_downloaded_script.erb

The main idea is to execute scripts from the Foreman server, similar to https://github.com/theforeman/foreman/pull/10208.

Fixes #37706 - Add a template that enables download and run of a script

---

webpack/JobWizard/JobWizardPageRerun.js
webpack/JobWizard/JobWizardSelectors.js
webpack/JobWizard/__tests__/fixtures.js
webpack/JobWizard/steps/ReviewDetails/ReviewDetails.test.js

Added a meaningful error message when trying to rerun a job with a nonexistent job template.
I think I may have overcomplicated it a bit - it was easy to display a "404" message, but I wanted the more concrete one.
TODO: fix the tests accordingly

Fixes #37447 - Add rerun job error

---

app/lib/actions/remote_execution/proxy_action.rb
app/lib/actions/remote_execution/run_host_job.rb
app/lib/actions/remote_execution/template_invocation_progress_logging.rb
db/migrate/20240312133027_extend_template_invocation_events.rb

Soft requires:
- https://github.com/theforeman/smart_proxy_dynflow/pull/135
- https://github.com/theforeman/smart_proxy_dynflow/pull/136

Fixes #37321 - Rely on output id when inserting events

---

app/controllers/api/v2/job_invocations_controller.rb
app/helpers/remote_execution_helper.rb
app/views/api/v2/job_invocations/hosts.json.rabl
config/routes.rb
webpack/JobInvocationDetail/JobInvocationActions.js
webpack/JobInvocationDetail/JobInvocationConstants.js
webpack/JobInvocationDetail/JobInvocationDetail.scss
webpack/JobInvocationDetail/JobInvocationHostTable.js
webpack/JobInvocationDetail/JobInvocationSelectors.js
webpack/JobInvocationDetail/__tests__/MainInformation.test.js
webpack/JobInvocationDetail/__tests__/fixtures.js
webpack/JobInvocationDetail/index.js
webpack/__mocks__/foremanReact/components/HostDetails/DetailsCard/DefaultLoaderEmptyState.js
webpack/react_app/components/RecentJobsCard/JobStatusIcon.js
webpack/react_app/components/RecentJobsCard/constants.js
webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/HostStatus.test.js.snap
webpack/react_app/components/TargetingHosts/components/HostStatus.js

Dependent on [this PR](https://github.com/theforeman/foreman_remote_execution/pull/899/commits/7c3c9edc42325faee3bd59f5a9a3a8660b80930e).
The next PR will add sorting, filtering by status, and permission handling.
The changes in the `JobStatusIcon` also affect the recent jobs card on the host detail page.

Fixes #37630 - Display basic list of hosts on the new job_invocations page

---

app/models/job_template.rb

To prevent importing templates which don't have their requirements met.
Requires https://github.com/theforeman/foreman/pull/10361
TODO:

Fixes #37962 - Check template requirements before import

---

app/views/template_invocations/show.js.erb

The same change as in https://github.com/theforeman/foreman_remote_execution/commit/8b169c26abe218ff549b5185411221dbd28ef14c#diff-0ed4202665b4981a38809478b2881a9f24aaf1e2fa48572d0f73bab06286d7e5L58
Overlooks happen :/

Fixes #38041 - Use Rails 7.0 style for rendering JS partials

---

db/migrate/20241126150849_remove_remote_execution_workers_pool_size.rb
lib/foreman_remote_execution/engine.rb

Sometimes the production.log is filled with a message: "Setting remote_execution_workers_pool_size has no definition, please define it before using"
This message does not appear to be a blocker to any of the existing functionalities, however; it is misleading while troubleshooting the issues.

Fixes #38022 - Do not use undefined setting

---

webpack/react_app/components/TargetingHosts/TargetingHostsPage.js
webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHostsPage.test.js.snap

Fixes #38101 - Align search bar with hosts list on job details page

---

webpack/JobWizard/JobWizard.js
webpack/JobWizard/StartsErrorAlert.js
webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
webpack/JobWizard/steps/Schedule/ScheduleFuture.js
webpack/JobWizard/steps/Schedule/ScheduleRecurring.js
webpack/JobWizard/steps/Schedule/ScheduleType.js
webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js
webpack/JobWizard/steps/form/DateTimePicker.js
webpack/JobWizard/steps/form/Formatter.js

Limited most of the date pickers to be only in the future (expect the user input one).
Added an error shown when the "starts at" is in the past.
Set the default value to starts at one minute on the future.
Updated the useEffect to set errors on "future" and "recurring" schedule, and to remove them otherwise.
Since I added a timer in the useEffect I added test fixes/ adjustments.

Fixes #38059 - job wizard limit starts at to future only

---

app/views/templates/script/convert2rhel_analyze.erb

ForemanAnsible: https://github.com/theforeman/foreman_ansible/pull/746/files
QE comments: https://github.com/theforeman/foreman_remote_execution/pull/933/files

Refs #38094 - Unify inputs in convert2rhel_analyze with ForemanAnsible template

---

app/controllers/api/v2/job_invocations_controller.rb
app/views/api/v2/job_invocations/base.json.rabl
app/views/api/v2/job_invocations/main.json.rabl
app/views/api/v2/job_invocations/show.json.rabl
webpack/JobInvocationDetail/JobAdditionInfo.js
webpack/JobInvocationDetail/JobInvocationConstants.js
webpack/JobInvocationDetail/JobInvocationDetail.scss
webpack/JobInvocationDetail/__tests__/fixtures.js
webpack/JobInvocationDetail/index.js

Adding info that was shown in `app/views/job_invocations/_card_*`

Fixes #38130 - add info to job details

---

webpack/JobInvocationDetail/JobInvocationDetail.scss
webpack/JobInvocationDetail/index.js

small fix for  https://github.com/theforeman/foreman_remote_execution/pull/939
JS code changes is just moving PageSection under pagelayout and adding a class name
before: 
after:

Refs #38130 - fix job details layout small screen

---

app/controllers/api/v2/job_invocations_controller.rb
webpack/JobInvocationDetail/JobInvocationConstants.js
webpack/JobInvocationDetail/JobInvocationHostTable.js
webpack/JobInvocationDetail/JobInvocationHostTableToolbar.js
webpack/JobInvocationDetail/JobInvocationSystemStatusChart.js
webpack/JobInvocationDetail/__tests__/MainInformation.test.js
webpack/JobInvocationDetail/index.js
webpack/react_app/components/TargetingHosts/components/HostStatus.js

Sorting and filtering were added to the host table of the new job invocation page.
(Ordering by status is not permitted on purpose.)
Needs [Fixes #38134 - Add custom pagination to table](https://github.com/theforeman/foreman/pull/10413)

Fixes #38090 - Add filtering to job invocation hosts table

---

app/controllers/job_invocations_controller.rb

For new hosts index page, use the search from the url when its used like: /job_invocations?feature=ansible_run_host&search=id%20^%20(63,50)
for example for the "run all ansible jobs" button when selecting hosts.
Without this the button doesnt run anything.
I didnt change the ui url calls to api since then we dont have the information on when to redirect to the job form or just run it.

Fixes #38202 - allow host search in job feature run

---

app/controllers/api/v2/job_templates_controller.rb

Currently, when importing a job template, taxonomies of the request are honored instead of taxonomies of the template itself. For an example see the Redmine issue.
The superclass [Template](https://github.com/theforeman/foreman/blob/develop/app/models/template.rb) of the class `JobTemplate` only extracts taxonomies from metadata on import if the option `:associate` is present, but this option is never accepted by the endpoint or assigned during the processing of the import request. I have added this option as a part of the `template_import_options` param group to stay consistent with imports of other template types.
The new behavior allows user to choose if the taxonomies of the request or the taxonomies in the template metadata should be honored based on the `options[associate]` param

Fixes #38263 - Assign correct taxonomies on template import

---

webpack/JobInvocationDetail/TemplateInvocationComponents/TemplateActionButtons.js

The patternfly style guide prefers Sentence case instead of Title Case.
Link: https://www.patternfly.org/ux-writing/capitalization
Fixes: 35cd0649f681 ("Fixes #38187 - Fix kebab items in job invocation (#947)")

Use sentence case for abort button task

---

.rubocop_todo.yml
app/controllers/cockpit_controller.rb
app/helpers/hosts_extensions_helper.rb
app/models/concerns/foreman_remote_execution/host_extensions.rb
app/models/script_execution_provider.rb
config/initializers/inflections.rb
lib/foreman_remote_execution/engine.rb
test/unit/actions/run_host_job_test.rb
test/unit/remote_execution_provider_test.rb

I was working in Katello and found that `reload!` from the console is broken (not returning `true`) for a number of reasons. One of them led to this plugin in relation to some aliasing that was introduced in #704 
The error was:
```
TypeError: superclass mismatch for class ScriptExecutionProvider
from /home/vagrant/foreman/.vendor/ruby/3.0.0/gems/foreman_remote_execution-16.0.3/app/models/ssh_execution_provider.rb:1:in `<main>'
```
This PR removes the `SSHExecutionProvider` constant while still providing 'ssh' as a provider by using `ScriptExecutionProvider` directly

Fixes #38461 - Replace SSHExecutionProvider with ScriptExecutionProvider

---

app/models/concerns/foreman_remote_execution/host_extensions.rb

Rebuilding a provisioned host in-place generates new host ssh keys, but does not reset the host-proxy mapping in the host_proxy_invocations table. As a result, the ssh keys are not pruned from the known hosts proxy file, and REX jobs won't succeed on the host because of the offending keys. Resetting host-proxy mapping solves this issue.

Fixes #38468 - Reset HostProxyInvocations when rebuilding a host

---

app/controllers/api/v2/job_templates_controller.rb
app/models/job_template.rb

- Use dup() instead of clone() to prevent locked status inheritance. 
- Add `deep_clone` method to handle taxonomies properly.

Fixes #38527 - Fix job template clone endpoint for locked templates

---

webpack/JobInvocationDetail/TemplateInvocation.js

Fixes #38495 - Fix memory leak bug in TemplateInvocation file

---

webpack/react_app/components/TargetingHosts/TargetingHostsLabelsRow.scss

css imports were moved in https://github.com/theforeman/foreman/pull/10345 already
and will break after https://github.com/theforeman/foreman/pull/10342 is merged.
This pr is only for the css import and can be merged now

Fixes #37906 - move css import from vendor to foreman

---

webpack/JobWizard/steps/HostsAndInputs/buildHostQuery.js

So its easier to see from the ui which hosts (/groups/collections) the job runs on

Fixes #38327 - build job names with host names

---

webpack/JobInvocationDetail/CheckboxesActions.js
webpack/JobInvocationDetail/__tests__/TableToolbarActions.test.js

in the job details table, when a user selects hosts and selects "rerun selected" the host query should include the job id to remove duplicate host entries in the job wizard.
Hopefully its a bug only in this one place

Fixes #38632 - Update job search in rerun to use job ID directly

---

webpack/JobInvocationDetail/JobInvocationHostTable.js
webpack/JobInvocationDetail/TemplateInvocation.js
webpack/JobInvocationDetail/TemplateInvocationPage.js
webpack/JobInvocationDetail/__tests__/TemplateInvocation.test.js
webpack/JobInvocationDetail/index.js

The index page now passes `finished` to the `JobInvocationHostTable`, and a `useEffect` is added to refetch the data when `finished` becomes true. I'm not sure if it's the best solution, even though it works as expected, so I'm open to new ideas.

Fixes #38636 - JobInvocationHostTable doesnt load the template with auto reload

---

webpack/JobInvocationDetail/JobInvocationHostTable.js
webpack/JobInvocationDetail/__tests__/MainInformation.test.js
webpack/JobInvocationDetail/index.js

Enables users to switch between adjacent jobs while maintaining context. Updates job details, data table, and charts dynamically when navigating.
Fixes: ac66cfb (Fixes #38599 - Sort out the loading of the new job invocation page)

Fixes #38773 - Add breadcrumb navigation to job invocation page
